# Generated by Django 3.0.8 on 2020-07-15 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0019_transactions_data_none'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirebaseDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_messaging_token', models.CharField(max_length=200)),
                ('build_number', models.PositiveIntegerField(default=0)),
                ('bundle', models.CharField(default='', max_length=100)),
                ('device_type', models.PositiveSmallIntegerField(choices=[(0, 'ANDROID'), (1, 'IOS'), (2, 'WEB')])),
                ('version', models.CharField(default='', max_length=50)),
                ('safe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firebase_tokens', to='history.SafeContract')),
            ],
            options={
                'verbose_name': 'Firebase Device',
                'verbose_name_plural': 'Firebase Devices',
                'unique_together': {('safe', 'cloud_messaging_token')},
            },
        ),
    ]
