# Generated by Django 3.0.8 on 2020-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firebasedevice",
            name="cloud_messaging_token",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
