# Generated by Django 3.1.3 on 2020-12-02 17:14

import django.db.models.deletion
from django.db import migrations, models

import gnosis.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_auto_20200806_1534"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirebaseDeviceOwner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", gnosis.eth.django.models.EthereumAddressField(db_index=True)),
                (
                    "firebase_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="notifications.firebasedevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firebase Device Owner",
                "verbose_name_plural": "Firebase Device Owners",
                "unique_together": {("firebase_device", "owner")},
            },
        ),
    ]
