# Generated by Django 3.2.9 on 2021-12-01 15:43

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_alter_firebasedeviceowner_id"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP INDEX IF EXISTS
                notifications_firebasede_safecontract_id_acb5c418_like,
                notifications_firebasedeviceowner_owner_025b0ed6_like;

            ALTER TABLE "notifications_firebasedeviceowner" ALTER COLUMN "owner" TYPE bytea USING DECODE(SUBSTRING("owner", 3), 'hex');
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="firebasedeviceowner",
            name="owner",
            field=gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
        ),
    ]
