# Generated by Django 4.2.10 on 2024-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_ethereum_address_field_v2"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="firebasedeviceowner",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="firebasedeviceowner",
            constraint=models.UniqueConstraint(
                fields=("firebase_device", "owner"), name="unique_firebase_device_owner"
            ),
        ),
    ]
