# Generated by Django 5.0.7 on 2024-07-19 12:53

from django.db import migrations

import safe_eth.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_firebasedeviceowner_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firebasedeviceowner",
            name="owner",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(db_index=True),
        ),
    ]
