# Generated by Django 5.0.3 on 2024-03-25 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields

import gnosis.eth.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("history", "0080_alter_multisigconfirmation_signature"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafeOperation",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "hash",
                    gnosis.eth.django.models.Keccak256Field(
                        primary_key=True, serialize=False
                    ),
                ),
                ("valid_after", models.DateTimeField(null=True)),
                ("valid_until", models.DateTimeField(null=True)),
                (
                    "module_address",
                    gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SafeOperationConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("owner", gnosis.eth.django.models.EthereumAddressV2Field()),
                (
                    "signature",
                    gnosis.eth.django.models.HexV2Field(
                        default=None, max_length=5000, null=True
                    ),
                ),
                (
                    "signature_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "CONTRACT_SIGNATURE"),
                            (1, "APPROVED_HASH"),
                            (2, "EOA"),
                            (3, "ETH_SIGN"),
                        ],
                        db_index=True,
                    ),
                ),
                (
                    "safe_operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmations",
                        to="account_abstraction.safeoperation",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="UserOperation",
            fields=[
                (
                    "hash",
                    gnosis.eth.django.models.Keccak256Field(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "sender",
                    gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
                ),
                ("nonce", gnosis.eth.django.models.Uint256Field()),
                ("init_code", models.BinaryField(blank=True, editable=True, null=True)),
                ("call_data", models.BinaryField(blank=True, editable=True, null=True)),
                ("call_data_gas_limit", gnosis.eth.django.models.Uint256Field()),
                ("verification_gas_limit", gnosis.eth.django.models.Uint256Field()),
                ("pre_verification_gas", gnosis.eth.django.models.Uint256Field()),
                ("max_fee_per_gas", gnosis.eth.django.models.Uint256Field()),
                ("max_priority_fee_per_gas", gnosis.eth.django.models.Uint256Field()),
                (
                    "paymaster",
                    gnosis.eth.django.models.EthereumAddressV2Field(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "paymaster_data",
                    models.BinaryField(blank=True, editable=True, null=True),
                ),
                ("signature", models.BinaryField(blank=True, editable=True, null=True)),
                (
                    "entry_point",
                    gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
                ),
                (
                    "ethereum_tx",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="history.ethereumtx",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="safeoperation",
            name="user_operation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safe_operation",
                to="account_abstraction.useroperation",
            ),
        ),
        migrations.CreateModel(
            name="UserOperationReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actual_gas_cost", gnosis.eth.django.models.Uint256Field()),
                ("actual_gas_used", gnosis.eth.django.models.Uint256Field()),
                ("success", models.BooleanField()),
                ("reason", models.CharField(max_length=256)),
                ("deposited", gnosis.eth.django.models.Uint256Field()),
                (
                    "user_operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="account_abstraction.useroperation",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="safeoperationconfirmation",
            constraint=models.UniqueConstraint(
                fields=("safe_operation", "owner"),
                name="unique_safe_operation_owner_confirmation",
            ),
        ),
        migrations.AddIndex(
            model_name="useroperation",
            index=models.Index(
                fields=["sender", "-nonce"], name="account_abs_sender_663a75_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useroperation",
            unique_together={("sender", "nonce")},
        ),
    ]
