# Generated by Django 4.2.10 on 2024-02-29 17:39

import django.db.models.deletion
from django.db import migrations, models

import gnosis.eth.django.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("history", "0078_remove_safestatus_history_saf_address_1c362b_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOperation",
            fields=[
                (
                    "user_operation_hash",
                    gnosis.eth.django.models.Keccak256Field(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "sender",
                    gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
                ),
                ("nonce", gnosis.eth.django.models.Uint256Field()),
                ("init_code", models.BinaryField(blank=True, editable=True, null=True)),
                ("call_data", models.BinaryField(blank=True, editable=True, null=True)),
                ("call_data_gas_limit", gnosis.eth.django.models.Uint256Field()),
                ("verification_gas_limit", gnosis.eth.django.models.Uint256Field()),
                ("pre_verification_gas", gnosis.eth.django.models.Uint256Field()),
                ("max_fee_per_gas", gnosis.eth.django.models.Uint256Field()),
                ("max_priority_fee_per_gas", gnosis.eth.django.models.Uint256Field()),
                (
                    "paymaster",
                    gnosis.eth.django.models.EthereumAddressV2Field(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "paymaster_data",
                    models.BinaryField(blank=True, editable=True, null=True),
                ),
                ("signature", models.BinaryField()),
                (
                    "entry_point",
                    gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
                ),
                (
                    "ethereum_tx",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="history.ethereumtx",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserOperationReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actual_gas_cost", gnosis.eth.django.models.Uint256Field()),
                ("actual_gas_used", gnosis.eth.django.models.Uint256Field()),
                ("success", models.BooleanField()),
                ("reason", models.CharField(max_length=256)),
                ("deposited", gnosis.eth.django.models.Uint256Field()),
                (
                    "user_operation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_abstraction.useroperation",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="useroperation",
            index=models.Index(
                fields=["sender", "-nonce"], name="account_abs_sender_663a75_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useroperation",
            unique_together={("sender", "nonce")},
        ),
    ]
