# Generated by Django 5.0.3 on 2024-04-05 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account_abstraction", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="useroperation",
            unique_together=set(),
        ),
    ]
