# Generated by Django 5.0.4 on 2024-05-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_abstraction", "0003_alter_useroperationreceipt_reason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useroperation",
            old_name="call_data_gas_limit",
            new_name="call_gas_limit",
        ),
    ]
