# Generated by Django 5.2.7 on 2025-10-28 17:35

import safe_eth.eth.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_abstraction', '0005_alter_safeoperation_module_address_and_more'),
        ('history', '0095_remove_internaltx_history_internaltx_value_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroperation',
            name='factory',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='useroperation',
            name='factory_data',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='useroperation',
            name='paymaster_post_op_gas_limit',
            field=safe_eth.eth.django.models.Uint256Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useroperation',
            name='paymaster_verification_gas_limit',
            field=safe_eth.eth.django.models.Uint256Field(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='useroperation',
            constraint=models.CheckConstraint(condition=models.Q(('factory__isnull', True), ('init_code__isnull', True), _connector='OR'), name='factory_or_init_code_not_both'),
        ),
        migrations.AddConstraint(
            model_name='useroperation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paymaster_data__isnull', True), ('paymaster_post_op_gas_limit__isnull', True), ('paymaster_verification_gas_limit__isnull', True)), ('paymaster__isnull', False), _connector='OR'), name='paymaster_required_with_paymaster_fields'),
        ),
        migrations.AddConstraint(
            model_name='useroperation',
            constraint=models.CheckConstraint(condition=models.Q(('init_code__isnull', True), models.Q(('paymaster_post_op_gas_limit__isnull', True), ('paymaster_verification_gas_limit__isnull', True)), _connector='OR'), name='v7_paymaster_gas_limits_not_with_init_code'),
        ),
        migrations.AddConstraint(
            model_name='useroperation',
            constraint=models.CheckConstraint(condition=models.Q(('factory_data__isnull', True), ('factory__isnull', False), _connector='OR'), name='factory_required_with_factory_data'),
        ),
    ]
