# Generated by Django 5.2.17 on 2026-10-01 11:12

import safe_eth.eth.django.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_abstraction', '0006_alter_safeoperationconfirmation_signature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroperation',
            name='sender',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
    ]
