# Generated by Django 5.2.17 on 2026-10-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_abstraction', '0007_alter_useroperation_sender'),
    ]

    # `AlterField` on a ForeignKey drops and recreates the FK constraint, which validates every row
    # while locking both tables. Only the index is dropped in the database, constraints are kept.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='safeoperationconfirmation',
                    name='safe_operation',
                    field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='account_abstraction.safeoperation'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX "account_abstraction_safeop_safe_operation_id_0bd247f6"',
                    reverse_sql='CREATE INDEX "account_abstraction_safeop_safe_operation_id_0bd247f6" ON "account_abstraction_safeoperationconfirmation" ("safe_operation_id")',
                ),
            ],
        ),
    ]
