# Generated by Django 5.2.15 on 2026-07-27 13:28

import django.db.models.deletion
import safe_eth.eth.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0101_multisigtransaction_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyContract',
            fields=[
                ('address', safe_eth.eth.django.models.EthereumAddressBinaryField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SafePolicyGuard',
            fields=[
                ('address', safe_eth.eth.django.models.EthereumAddressBinaryField(primary_key=True, serialize=False)),
                ('initial_block_number', models.IntegerField(default=0)),
                ('tx_block_number', models.IntegerField(db_index=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Safe policy guard',
                'verbose_name_plural': 'Safe policy guards',
                'ordering': ['tx_block_number'],
            },
        ),
        migrations.CreateModel(
            name='PolicyConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_index', models.PositiveIntegerField()),
                ('block_number', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('guard', safe_eth.eth.django.models.EthereumAddressBinaryField()),
                ('safe', safe_eth.eth.django.models.EthereumAddressBinaryField(db_index=True)),
                ('target', safe_eth.eth.django.models.EthereumAddressBinaryField()),
                ('selector', safe_eth.eth.django.models.HexV2Field(max_length=4)),
                ('operation', models.PositiveSmallIntegerField(choices=[(0, 'CALL'), (1, 'DELEGATE_CALL')])),
                ('policy', safe_eth.eth.django.models.EthereumAddressBinaryField(db_index=True)),
                ('data', models.BinaryField(blank=True)),
                ('ethereum_tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.ethereumtx')),
            ],
            options={
                'indexes': [models.Index(fields=['safe', '-timestamp'], name='policies_po_safe_3c3eef_idx'), models.Index(fields=['safe', 'target', 'selector', 'operation', '-block_number', '-log_index'], name='policy_confirmation_access')],
                'constraints': [models.UniqueConstraint(fields=('ethereum_tx', 'log_index'), name='unique_policy_confirmation_log')],
            },
        ),
        migrations.CreateModel(
            name='PolicyRootInvalidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_index', models.PositiveIntegerField()),
                ('block_number', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('guard', safe_eth.eth.django.models.EthereumAddressBinaryField()),
                ('safe', safe_eth.eth.django.models.EthereumAddressBinaryField(db_index=True)),
                ('root', safe_eth.eth.django.models.Keccak256Field(db_index=True)),
                ('ethereum_tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.ethereumtx')),
            ],
            options={
                'indexes': [models.Index(fields=['safe', '-timestamp'], name='policies_po_safe_4de97e_idx')],
                'constraints': [models.UniqueConstraint(fields=('ethereum_tx', 'log_index'), name='unique_policy_root_invalidation_log')],
            },
        ),
        migrations.CreateModel(
            name='PolicyRootRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_index', models.PositiveIntegerField()),
                ('block_number', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('guard', safe_eth.eth.django.models.EthereumAddressBinaryField()),
                ('safe', safe_eth.eth.django.models.EthereumAddressBinaryField(db_index=True)),
                ('root', safe_eth.eth.django.models.Keccak256Field(db_index=True)),
                ('valid_from', models.DateTimeField()),
                ('ethereum_tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.ethereumtx')),
            ],
            options={
                'indexes': [models.Index(fields=['safe', '-timestamp'], name='policies_po_safe_a1aa90_idx')],
                'constraints': [models.UniqueConstraint(fields=('ethereum_tx', 'log_index'), name='unique_policy_root_request_log')],
            },
        ),
    ]
