# Generated by Django 3.2.11 on 2022-02-01 13:35

from django.db import migrations, models

import safe_transaction_service.tokens.models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0004_ethereum_address_field_v2_20211201_1512"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="token",
            name="logo_uri",
        ),
        migrations.AddField(
            model_name="token",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to=safe_transaction_service.tokens.models.get_token_logo_path,
            ),
        ),
    ]
