# Generated by Django 3.2.12 on 2022-02-14 16:29

from django.db import migrations, models

import gnosis.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0005_add_logo_file_20220201_1335"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="copy_price",
            field=gnosis.eth.django.models.EthereumAddressV2Field(
                help_text="If provided, copy the price from the token", null=True
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="decimals",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                help_text="Number of decimals. For ERC721 tokens decimals must be `None`",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="events_bugged",
            field=models.BooleanField(
                default=False,
                help_text="Set `True` if token does not send `Transfer` event sometimes (e.g. WETH on minting)",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="spam",
            field=models.BooleanField(
                default=False, help_text="Spam and trusted cannot be both True"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="trusted",
            field=models.BooleanField(
                default=False, help_text="Spam and trusted cannot be both True"
            ),
        ),
    ]
