# Generated by Django 3.2.13 on 2022-07-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0008_alter_token_copy_price"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                condition=models.Q(("spam", True)),
                fields=["spam"],
                name="token_spam_idx",
            ),
        ),
    ]
