# Generated by Django 5.0.9 on 2024-10-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0012_alter_token_address_alter_token_copy_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="logo_uri",
            field=models.URLField(
                blank=True,
                default="",
                help_text="If provided, return this URI instead of the stored logo",
            ),
        ),
    ]
