# Generated by Django 5.0.9 on 2024-11-12 13:38

from django.db import migrations

import safe_eth.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0013_token_logo_uri"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenNotValid",
            fields=[
                (
                    "address",
                    safe_eth.eth.django.models.EthereumAddressBinaryField(
                        primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
    ]
