# Generated by Django 5.2.5 on 2025-12-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0014_tokennotvalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenlist',
            name='auth_key',
            field=models.CharField(blank=True, help_text="Authentication key name. Usage depends on auth_type: For 'api_key': header name (e.g., 'x-api-key'). For 'bearer': header name (e.g., 'Authorization'). For 'query': query parameter name (e.g., 'api_key'). For 'basic': leave empty. For 'none': leave empty.", max_length=100),
        ),
        migrations.AddField(
            model_name='tokenlist',
            name='auth_type',
            field=models.CharField(choices=[('none', 'None'), ('api_key', 'API Key (Header)'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('query', 'Query Param')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='tokenlist',
            name='auth_value',
            field=models.TextField(blank=True, help_text="Authentication credentials. Usage depends on auth_type: For 'api_key': the API key value. For 'bearer': the bearer token value (without 'Bearer ' prefix). For 'basic': the full 'Basic <base64>' value (e.g., 'Basic dXNlcjpwYXNz'). For 'query': the query parameter value. For 'none': leave empty."),
        ),
    ]
