# Generated by Django 5.2.5 on 2025-12-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0014_tokennotvalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenlist',
            name='auth_key',
            field=models.CharField(blank=True, help_text='Header name or query param name (e.g. api_key, token)', max_length=100),
        ),
        migrations.AddField(
            model_name='tokenlist',
            name='auth_type',
            field=models.CharField(choices=[('none', 'None'), ('api_key', 'API Key (Header)'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('query', 'Query Param')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='tokenlist',
            name='auth_value',
            field=models.TextField(blank=True, help_text='Token / API key / credentials'),
        ),
    ]
