# Generated by Django 2.0.6 on 2018-07-03 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import safe_transaction_history.safe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('owner', safe_transaction_history.safe.models.EthereumAddressField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultisigTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('safe', safe_transaction_history.safe.models.EthereumAddressField()),
                ('to', safe_transaction_history.safe.models.EthereumAddressField()),
                ('value', models.PositiveIntegerField()),
                ('data', models.TextField()),
                ('operation', models.PositiveIntegerField()),
                ('nonce', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='confirmation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe.MultisigTransaction'),
        ),
    ]
