# Generated by Django 2.0.6 on 2018-07-25 08:43

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models

import safe_transaction_history.safe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultisigConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('owner', safe_transaction_history.safe.models.EthereumAddressField()),
                ('contract_transaction_hash', models.CharField(max_length=66)),
                ('transaction_hash', models.CharField(max_length=66)),
                ('block_number', models.IntegerField()),
                ('block_date_time', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultisigTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('safe', safe_transaction_history.safe.models.EthereumAddressField()),
                ('to', safe_transaction_history.safe.models.EthereumAddressField()),
                ('value', models.BigIntegerField()),
                ('data', models.BinaryField(null=True)),
                ('operation', models.PositiveSmallIntegerField()),
                ('nonce', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='multisigconfirmation',
            name='multisig_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='safe.MultisigTransaction'),
        ),
    ]
