# Generated by Django 2.0.6 on 2018-07-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Confirmation',
            new_name='MultisigConfirmation',
        ),
        migrations.AlterField(
            model_name='multisigtransaction',
            name='data',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='multisigtransaction',
            name='operation',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='multisigtransaction',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
