# Generated by Django 2.0.7 on 2018-07-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigconfirmation',
            name='type',
            field=models.CharField(default='confirmation', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multisigtransaction',
            name='execution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
