# Generated by Django 2.0.6 on 2018-07-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0002_auto_20180704_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigtransaction',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
