# Generated by Django 2.0.8 on 2018-08-13 11:30

from django.db import migrations, models

import django_eth.models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0003_auto_20180808_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multisigconfirmation',
            name='block_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='multisigconfirmation',
            name='contract_transaction_hash',
            field=django_eth.models.Sha3HashField(),
        ),
        migrations.AlterField(
            model_name='multisigconfirmation',
            name='transaction_hash',
            field=django_eth.models.Sha3HashField(),
        ),
        migrations.AlterField(
            model_name='multisigtransaction',
            name='nonce',
            field=django_eth.models.Uint256Field(),
        ),
        migrations.AlterField(
            model_name='multisigtransaction',
            name='value',
            field=django_eth.models.Uint256Field(),
        ),
    ]
