# Generated by Django 2.0.6 on 2018-07-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0003_multisigtransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multisigtransaction',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
