# Generated by Django 2.0.6 on 2018-07-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0004_auto_20180709_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multisigtransaction',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
