# Generated by Django 2.0.6 on 2018-07-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0005_auto_20180710_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigconfirmation',
            name='transaction_hash',
            field=models.CharField(default='0x0', max_length=66),
            preserve_default=False,
        ),
    ]
