# Generated by Django 2.0.6 on 2018-07-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0006_multisigconfirmation_transaction_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multisigconfirmation',
            old_name='transaction',
            new_name='multisig_transaction',
        ),
    ]
