# Generated by Django 2.0.6 on 2018-07-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0007_auto_20180710_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigconfirmation',
            name='contract_transaction_hash',
            field=models.CharField(default='0x0', max_length=66),
            preserve_default=False,
        ),
    ]
