# Generated by Django 2.0.6 on 2018-07-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0008_multisigconfirmation_contract_transaction_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigconfirmation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
