# Generated by Django 2.0.6 on 2018-07-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0009_multisigconfirmation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multisigconfirmation',
            name='transaction_hash',
        ),
        migrations.AlterField(
            model_name='multisigconfirmation',
            name='multisig_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='safe.MultisigTransaction'),
        ),
    ]
