# Less size than Debian
FROM python:3.13.7-alpine

ARG APP_HOME=/app
WORKDIR ${APP_HOME}
ENV PYTHONUNBUFFERED=1

# https://eth-hash.readthedocs.io/en/latest/quickstart.html#specify-backend-by-environment-variable
# `pysha3` is way faster than `pycryptodome` for CPython
ENV ETH_HASH_BACKEND=pysha3

COPY requirements.txt ./
RUN set -ex && \
    apk add --update --no-cache postgresql-client tmux && \
    apk add --no-cache --virtual .build-dependencies postgresql-dev alpine-sdk libffi-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del .build-dependencies && \
    find /usr/local \
        \( -type d -a -name test -o -name tests \) \
        -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
        -exec rm -rf '{}' +

RUN addgroup -g 999 -S python && \
    adduser -u 999 -S python python && \
    mkdir -p /nginx && \
    chown -R python:python /nginx ${APP_HOME}
COPY --chown=python:python . .

# Use numeric ids so kubernetes identifies the user correctly
USER 999:999

RUN DJANGO_SETTINGS_MODULE=config.settings.production DJANGO_DOT_ENV_FILE=.env.tracing.sample python manage.py collectstatic --noinput
