# noqa

sourcify_safe_metadata = {'compiler': {'version': '0.5.17+commit.d19bba13'},
                          'language': 'Solidity',
                          'output': {'abi': [{'inputs': [],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'constructor'},
                                             {'anonymous': False,
                                              'inputs': [{'indexed': False,
                                                          'internalType': 'address',
                                                          'name': 'owner',
                                                          'type': 'address'}],
                                              'name': 'AddedOwner',
                                              'type': 'event'},
                                             {'anonymous': False,
                                              'inputs': [{'indexed': True,
                                                          'internalType': 'bytes32',
                                                          'name': 'approvedHash',
                                                          'type': 'bytes32'},
                                                         {'indexed': True,
                                                          'internalType': 'address',
                                                          'name': 'owner',
                                                          'type': 'address'}],
                                              'name': 'ApproveHash',
                                              'type': 'event'},
                                             {'anonymous': False,
                                              'inputs': [{'indexed': False,
                                                          'internalType': 'address',
                                                          'name': 'masterCopy',
                                                          'type': 'address'}],
                                              'name': 'ChangedMasterCopy',
                                              'type': 'event'},
                                             {'anonymous': False,
                                              'inputs': [{'indexed': False,
                                                          'internalType': 'uint256',
                                                          'name': 'threshold',
                                                          'type': 'uint256'}],
                                              'name': 'ChangedThreshold',
                                              'type': 'event'},
                                             {'anonymous': False,
                                              'inputs': [{'indexed': False,
                                                          'internalType': 'contract Module',
                                                          'name': 'module',
                                                          'type': 'address'}],
                                              'name': 'DisabledModule',
                                              'type': 'event'},
                                             {'anonymous': False,
                                              'inputs': [{'indexed': False,
                                                          'internalType': 'contract Module',
                                                          'name': 'module',
                                                          'type': 'address'}],
                                              'name': 'EnabledModule',
                                              'type': 'event'},
                                             {'anonymous': False,
                                              'inputs': [{'indexed': False,
                                                          'internalType': 'bytes32',
                                                          'name': 'txHash',
                                                          'type': 'bytes32'},
                                                         {'indexed': False,
                                                          'internalType': 'uint256',
                                                          'name': 'payment',
                                                          'type': 'uint256'}],
                                              'name': 'ExecutionFailure',
                                              'type': 'event'},
                                             {'anonymous': False,
                                              'inputs': [{'indexed': True,
                                                          'internalType': 'address',
                                                          'name': 'module',
                                                          'type': 'address'}],
                                              'name': 'ExecutionFromModuleFailure',
                                              'type': 'event'},
                                             {'anonymous': False,
                                              'inputs': [{'indexed': True,
                                                          'internalType': 'address',
                                                          'name': 'module',
                                                          'type': 'address'}],
                                              'name': 'ExecutionFromModuleSuccess',
                                              'type': 'event'},
                                             {'anonymous': False,
                                              'inputs': [{'indexed': False,
                                                          'internalType': 'bytes32',
                                                          'name': 'txHash',
                                                          'type': 'bytes32'},
                                                         {'indexed': False,
                                                          'internalType': 'uint256',
                                                          'name': 'payment',
                                                          'type': 'uint256'}],
                                              'name': 'ExecutionSuccess',
                                              'type': 'event'},
                                             {'anonymous': False,
                                              'inputs': [{'indexed': False,
                                                          'internalType': 'address',
                                                          'name': 'owner',
                                                          'type': 'address'}],
                                              'name': 'RemovedOwner',
                                              'type': 'event'},
                                             {'anonymous': False,
                                              'inputs': [{'indexed': True,
                                                          'internalType': 'bytes32',
                                                          'name': 'msgHash',
                                                          'type': 'bytes32'}],
                                              'name': 'SignMsg',
                                              'type': 'event'},
                                             {'payable': True, 'stateMutability': 'payable', 'type': 'fallback'},
                                             {'constant': True,
                                              'inputs': [],
                                              'name': 'NAME',
                                              'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': True,
                                              'inputs': [],
                                              'name': 'VERSION',
                                              'outputs': [{'internalType': 'string', 'name': '', 'type': 'string'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'address', 'name': 'owner', 'type': 'address'},
                                                         {'internalType': 'uint256', 'name': '_threshold', 'type': 'uint256'}],
                                              'name': 'addOwnerWithThreshold',
                                              'outputs': [],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'bytes32',
                                                          'name': 'hashToApprove',
                                                          'type': 'bytes32'}],
                                              'name': 'approveHash',
                                              'outputs': [],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'},
                                             {'constant': True,
                                              'inputs': [{'internalType': 'address', 'name': '', 'type': 'address'},
                                                         {'internalType': 'bytes32', 'name': '', 'type': 'bytes32'}],
                                              'name': 'approvedHashes',
                                              'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'address',
                                                          'name': '_masterCopy',
                                                          'type': 'address'}],
                                              'name': 'changeMasterCopy',
                                              'outputs': [],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'uint256',
                                                          'name': '_threshold',
                                                          'type': 'uint256'}],
                                              'name': 'changeThreshold',
                                              'outputs': [],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'contract Module',
                                                          'name': 'prevModule',
                                                          'type': 'address'},
                                                         {'internalType': 'contract Module', 'name': 'module', 'type': 'address'}],
                                              'name': 'disableModule',
                                              'outputs': [],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'},
                                             {'constant': True,
                                              'inputs': [],
                                              'name': 'domainSeparator',
                                              'outputs': [{'internalType': 'bytes32', 'name': '', 'type': 'bytes32'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'contract Module',
                                                          'name': 'module',
                                                          'type': 'address'}],
                                              'name': 'enableModule',
                                              'outputs': [],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'},
                                             {'constant': True,
                                              'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'},
                                                         {'internalType': 'uint256', 'name': 'value', 'type': 'uint256'},
                                                         {'internalType': 'bytes', 'name': 'data', 'type': 'bytes'},
                                                         {'internalType': 'enum Enum.Operation',
                                                          'name': 'operation',
                                                          'type': 'uint8'},
                                                         {'internalType': 'uint256', 'name': 'safeTxGas', 'type': 'uint256'},
                                                         {'internalType': 'uint256', 'name': 'baseGas', 'type': 'uint256'},
                                                         {'internalType': 'uint256', 'name': 'gasPrice', 'type': 'uint256'},
                                                         {'internalType': 'address', 'name': 'gasToken', 'type': 'address'},
                                                         {'internalType': 'address', 'name': 'refundReceiver', 'type': 'address'},
                                                         {'internalType': 'uint256', 'name': '_nonce', 'type': 'uint256'}],
                                              'name': 'encodeTransactionData',
                                              'outputs': [{'internalType': 'bytes', 'name': '', 'type': 'bytes'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'},
                                                         {'internalType': 'uint256', 'name': 'value', 'type': 'uint256'},
                                                         {'internalType': 'bytes', 'name': 'data', 'type': 'bytes'},
                                                         {'internalType': 'enum Enum.Operation',
                                                          'name': 'operation',
                                                          'type': 'uint8'},
                                                         {'internalType': 'uint256', 'name': 'safeTxGas', 'type': 'uint256'},
                                                         {'internalType': 'uint256', 'name': 'baseGas', 'type': 'uint256'},
                                                         {'internalType': 'uint256', 'name': 'gasPrice', 'type': 'uint256'},
                                                         {'internalType': 'address', 'name': 'gasToken', 'type': 'address'},
                                                         {'internalType': 'address payable',
                                                          'name': 'refundReceiver',
                                                          'type': 'address'},
                                                         {'internalType': 'bytes', 'name': 'signatures', 'type': 'bytes'}],
                                              'name': 'execTransaction',
                                              'outputs': [{'internalType': 'bool', 'name': 'success', 'type': 'bool'}],
                                              'payable': True,
                                              'stateMutability': 'payable',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'},
                                                         {'internalType': 'uint256', 'name': 'value', 'type': 'uint256'},
                                                         {'internalType': 'bytes', 'name': 'data', 'type': 'bytes'},
                                                         {'internalType': 'enum Enum.Operation',
                                                          'name': 'operation',
                                                          'type': 'uint8'}],
                                              'name': 'execTransactionFromModule',
                                              'outputs': [{'internalType': 'bool', 'name': 'success', 'type': 'bool'}],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'},
                                                         {'internalType': 'uint256', 'name': 'value', 'type': 'uint256'},
                                                         {'internalType': 'bytes', 'name': 'data', 'type': 'bytes'},
                                                         {'internalType': 'enum Enum.Operation',
                                                          'name': 'operation',
                                                          'type': 'uint8'}],
                                              'name': 'execTransactionFromModuleReturnData',
                                              'outputs': [{'internalType': 'bool', 'name': 'success', 'type': 'bool'},
                                                          {'internalType': 'bytes', 'name': 'returnData', 'type': 'bytes'}],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'},
                                             {'constant': True,
                                              'inputs': [{'internalType': 'bytes', 'name': 'message', 'type': 'bytes'}],
                                              'name': 'getMessageHash',
                                              'outputs': [{'internalType': 'bytes32', 'name': '', 'type': 'bytes32'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': True,
                                              'inputs': [],
                                              'name': 'getModules',
                                              'outputs': [{'internalType': 'address[]',
                                                           'name': '',
                                                           'type': 'address[]'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': True,
                                              'inputs': [{'internalType': 'address', 'name': 'start', 'type': 'address'},
                                                         {'internalType': 'uint256', 'name': 'pageSize', 'type': 'uint256'}],
                                              'name': 'getModulesPaginated',
                                              'outputs': [{'internalType': 'address[]',
                                                           'name': 'array',
                                                           'type': 'address[]'},
                                                          {'internalType': 'address', 'name': 'next', 'type': 'address'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': True,
                                              'inputs': [],
                                              'name': 'getOwners',
                                              'outputs': [{'internalType': 'address[]',
                                                           'name': '',
                                                           'type': 'address[]'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': True,
                                              'inputs': [],
                                              'name': 'getThreshold',
                                              'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': True,
                                              'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'},
                                                         {'internalType': 'uint256', 'name': 'value', 'type': 'uint256'},
                                                         {'internalType': 'bytes', 'name': 'data', 'type': 'bytes'},
                                                         {'internalType': 'enum Enum.Operation',
                                                          'name': 'operation',
                                                          'type': 'uint8'},
                                                         {'internalType': 'uint256', 'name': 'safeTxGas', 'type': 'uint256'},
                                                         {'internalType': 'uint256', 'name': 'baseGas', 'type': 'uint256'},
                                                         {'internalType': 'uint256', 'name': 'gasPrice', 'type': 'uint256'},
                                                         {'internalType': 'address', 'name': 'gasToken', 'type': 'address'},
                                                         {'internalType': 'address', 'name': 'refundReceiver', 'type': 'address'},
                                                         {'internalType': 'uint256', 'name': '_nonce', 'type': 'uint256'}],
                                              'name': 'getTransactionHash',
                                              'outputs': [{'internalType': 'bytes32', 'name': '', 'type': 'bytes32'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': True,
                                              'inputs': [{'internalType': 'contract Module',
                                                          'name': 'module',
                                                          'type': 'address'}],
                                              'name': 'isModuleEnabled',
                                              'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': True,
                                              'inputs': [{'internalType': 'address',
                                                          'name': 'owner',
                                                          'type': 'address'}],
                                              'name': 'isOwner',
                                              'outputs': [{'internalType': 'bool', 'name': '', 'type': 'bool'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'bytes', 'name': '_data', 'type': 'bytes'},
                                                         {'internalType': 'bytes', 'name': '_signature', 'type': 'bytes'}],
                                              'name': 'isValidSignature',
                                              'outputs': [{'internalType': 'bytes4', 'name': '', 'type': 'bytes4'}],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'},
                                             {'constant': True,
                                              'inputs': [],
                                              'name': 'nonce',
                                              'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'address',
                                                          'name': 'prevOwner',
                                                          'type': 'address'},
                                                         {'internalType': 'address', 'name': 'owner', 'type': 'address'},
                                                         {'internalType': 'uint256', 'name': '_threshold', 'type': 'uint256'}],
                                              'name': 'removeOwner',
                                              'outputs': [],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'address', 'name': 'to', 'type': 'address'},
                                                         {'internalType': 'uint256', 'name': 'value', 'type': 'uint256'},
                                                         {'internalType': 'bytes', 'name': 'data', 'type': 'bytes'},
                                                         {'internalType': 'enum Enum.Operation',
                                                          'name': 'operation',
                                                          'type': 'uint8'}],
                                              'name': 'requiredTxGas',
                                              'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'address',
                                                          'name': 'handler',
                                                          'type': 'address'}],
                                              'name': 'setFallbackHandler',
                                              'outputs': [],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'address[]',
                                                          'name': '_owners',
                                                          'type': 'address[]'},
                                                         {'internalType': 'uint256', 'name': '_threshold', 'type': 'uint256'},
                                                         {'internalType': 'address', 'name': 'to', 'type': 'address'},
                                                         {'internalType': 'bytes', 'name': 'data', 'type': 'bytes'},
                                                         {'internalType': 'address', 'name': 'fallbackHandler', 'type': 'address'},
                                                         {'internalType': 'address', 'name': 'paymentToken', 'type': 'address'},
                                                         {'internalType': 'uint256', 'name': 'payment', 'type': 'uint256'},
                                                         {'internalType': 'address payable',
                                                          'name': 'paymentReceiver',
                                                          'type': 'address'}],
                                              'name': 'setup',
                                              'outputs': [],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'bytes', 'name': '_data', 'type': 'bytes'}],
                                              'name': 'signMessage',
                                              'outputs': [],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'},
                                             {'constant': True,
                                              'inputs': [{'internalType': 'bytes32', 'name': '', 'type': 'bytes32'}],
                                              'name': 'signedMessages',
                                              'outputs': [{'internalType': 'uint256', 'name': '', 'type': 'uint256'}],
                                              'payable': False,
                                              'stateMutability': 'view',
                                              'type': 'function'},
                                             {'constant': False,
                                              'inputs': [{'internalType': 'address',
                                                          'name': 'prevOwner',
                                                          'type': 'address'},
                                                         {'internalType': 'address', 'name': 'oldOwner', 'type': 'address'},
                                                         {'internalType': 'address', 'name': 'newOwner', 'type': 'address'}],
                                              'name': 'swapOwner',
                                              'outputs': [],
                                              'payable': False,
                                              'stateMutability': 'nonpayable',
                                              'type': 'function'}],
                                     'devdoc': {'author': 'Stefan George - <stefan@gnosis.io>Richard Meissner - <richard@gnosis.io>Ricardo Guilherme Schmidt - (Status Research & Development GmbH) - Gas Token Payment',
                                                'methods': {'addOwnerWithThreshold(address,uint256)': {'details': 'Allows to add a new owner to the Safe and update the threshold at the same time.      This can only be done via a Safe transaction.',
                                                                                                       'params': {'_threshold': 'New threshold.',
                                                                                                                  'owner': 'New owner address.'}},
                                                            'approveHash(bytes32)': {'details': 'Marks a hash as approved. This can be used to validate a hash that is used by a signature.',
                                                                                     'params': {'hashToApprove': 'The hash that should be marked as approved for signatures that are verified by this contract.'}},
                                                            'changeMasterCopy(address)': {'details': 'Allows to upgrade the contract. This can only be done via a Safe transaction.',
                                                                                          'params': {'_masterCopy': 'New contract address.'}},
                                                            'changeThreshold(uint256)': {'details': 'Allows to update the number of required confirmations by Safe owners.      This can only be done via a Safe transaction.',
                                                                                         'params': {'_threshold': 'New threshold.'}},
                                                            'disableModule(address,address)': {'details': 'Allows to remove a module from the whitelist.      This can only be done via a Safe transaction.',
                                                                                               'params': {'module': 'Module to be removed.',
                                                                                                          'prevModule': 'Module that pointed to the module to be removed in the linked list'}},
                                                            'enableModule(address)': {'details': 'Allows to add a module to the whitelist.      This can only be done via a Safe transaction.',
                                                                                      'params': {'module': 'Module to be whitelisted.'}},
                                                            'encodeTransactionData(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,uint256)': {'details': 'Returns the bytes that are hashed to be signed by owners.',
                                                                                                                                                                   'params': {'_nonce': 'Transaction nonce.',
                                                                                                                                                                              'baseGas': 'Gas costs for data used to trigger the safe transaction.',
                                                                                                                                                                              'data': 'Data payload.',
                                                                                                                                                                              'gasPrice': 'Maximum gas price that should be used for this transaction.',
                                                                                                                                                                              'gasToken': 'Token address (or 0 if ETH) that is used for the payment.',
                                                                                                                                                                              'operation': 'Operation type.',
                                                                                                                                                                              'refundReceiver': 'Address of receiver of gas payment (or 0 if tx.origin).',
                                                                                                                                                                              'safeTxGas': 'Fas that should be used for the safe transaction.',
                                                                                                                                                                              'to': 'Destination address.',
                                                                                                                                                                              'value': 'Ether value.'},
                                                                                                                                                                   'return': 'Transaction hash bytes.'},
                                                            'execTransaction(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,bytes)': {'details': 'Allows to execute a Safe transaction confirmed by required number of owners and then pays the account that submitted the transaction.      Note: The fees are always transfered, even if the user transaction fails.',
                                                                                                                                                           'params': {'baseGas': 'Gas costs for that are indipendent of the transaction execution(e.g. base transaction fee, signature check, payment of the refund)',
                                                                                                                                                                      'data': 'Data payload of Safe transaction.',
                                                                                                                                                                      'gasPrice': 'Gas price that should be used for the payment calculation.',
                                                                                                                                                                      'gasToken': 'Token address (or 0 if ETH) that is used for the payment.',
                                                                                                                                                                      'operation': 'Operation type of Safe transaction.',
                                                                                                                                                                      'refundReceiver': 'Address of receiver of gas payment (or 0 if tx.origin).',
                                                                                                                                                                      'safeTxGas': 'Gas that should be used for the Safe transaction.',
                                                                                                                                                                      'signatures': 'Packed signature data ({bytes32 r}{bytes32 s}{uint8 v})',
                                                                                                                                                                      'to': 'Destination address of Safe transaction.',
                                                                                                                                                                      'value': 'Ether value of Safe transaction.'}},
                                                            'execTransactionFromModule(address,uint256,bytes,uint8)': {'details': 'Allows a Module to execute a Safe transaction without any further confirmations.',
                                                                                                                       'params': {'data': 'Data payload of module transaction.',
                                                                                                                                  'operation': 'Operation type of module transaction.',
                                                                                                                                  'to': 'Destination address of module transaction.',
                                                                                                                                  'value': 'Ether value of module transaction.'}},
                                                            'execTransactionFromModuleReturnData(address,uint256,bytes,uint8)': {'details': 'Allows a Module to execute a Safe transaction without any further confirmations and return data',
                                                                                                                                 'params': {'data': 'Data payload of module transaction.',
                                                                                                                                            'operation': 'Operation type of module transaction.',
                                                                                                                                            'to': 'Destination address of module transaction.',
                                                                                                                                            'value': 'Ether value of module transaction.'}},
                                                            'getMessageHash(bytes)': {'details': 'Returns hash of a message that can be signed by owners.',
                                                                                      'params': {'message': 'Message that should be hashed'},
                                                                                      'return': 'Message hash.'},
                                                            'getModules()': {'details': 'Returns array of first 10 modules.',
                                                                             'return': 'Array of modules.'},
                                                            'getModulesPaginated(address,uint256)': {'details': 'Returns array of modules.',
                                                                                                     'params': {'pageSize': 'Maximum number of modules that should be returned.',
                                                                                                                'start': 'Start of the page.'},
                                                                                                     'return': 'Array of modules.'},
                                                            'getOwners()': {'details': 'Returns array of owners.',
                                                                            'return': 'Array of Safe owners.'},
                                                            'getTransactionHash(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,uint256)': {'details': 'Returns hash to be signed by owners.',
                                                                                                                                                                'params': {'_nonce': 'Transaction nonce.',
                                                                                                                                                                           'baseGas': 'Gas costs for data used to trigger the safe transaction.',
                                                                                                                                                                           'data': 'Data payload.',
                                                                                                                                                                           'gasPrice': 'Maximum gas price that should be used for this transaction.',
                                                                                                                                                                           'gasToken': 'Token address (or 0 if ETH) that is used for the payment.',
                                                                                                                                                                           'operation': 'Operation type.',
                                                                                                                                                                           'refundReceiver': 'Address of receiver of gas payment (or 0 if tx.origin).',
                                                                                                                                                                           'safeTxGas': 'Fas that should be used for the safe transaction.',
                                                                                                                                                                           'to': 'Destination address.',
                                                                                                                                                                           'value': 'Ether value.'},
                                                                                                                                                                'return': 'Transaction hash.'},
                                                            'isModuleEnabled(address)': {'details': 'Returns if an module is enabled',
                                                                                         'return': 'True if the module is enabled'},
                                                            'isValidSignature(bytes,bytes)': {'details': 'Should return whether the signature provided is valid for the provided data.      The save does not implement the interface since `checkSignatures` is not a view method.      The method will not perform any state changes (see parameters of `checkSignatures`)',
                                                                                              'params': {'_data': 'Arbitrary length data signed on the behalf of address(this)',
                                                                                                         '_signature': 'Signature byte array associated with _data'},
                                                                                              'return': 'a bool upon valid or invalid signature with corresponding _data'},
                                                            'removeOwner(address,address,uint256)': {'details': 'Allows to remove an owner from the Safe and update the threshold at the same time.      This can only be done via a Safe transaction.',
                                                                                                     'params': {'_threshold': 'New threshold.',
                                                                                                                'owner': 'Owner address to be removed.',
                                                                                                                'prevOwner': 'Owner that pointed to the owner to be removed in the linked list'}},
                                                            'requiredTxGas(address,uint256,bytes,uint8)': {'details': 'Allows to estimate a Safe transaction.      This method is only meant for estimation purpose, therefore two different protection mechanism against execution in a transaction have been made:      1.) The method can only be called from the safe itself      2.) The response is returned with a revert      When estimating set `from` to the address of the safe.      Since the `estimateGas` function includes refunds, call this method to get an estimated of the costs that are deducted from the safe with `execTransaction`',
                                                                                                           'params': {'data': 'Data payload of Safe transaction.',
                                                                                                                      'operation': 'Operation type of Safe transaction.',
                                                                                                                      'to': 'Destination address of Safe transaction.',
                                                                                                                      'value': 'Ether value of Safe transaction.'},
                                                                                                           'return': 'Estimate without refunds and overhead fees (base transaction and payload data gas costs).'},
                                                            'setFallbackHandler(address)': {'details': 'Allows to add a contract to handle fallback calls.      Only fallback calls without value and with data will be forwarded.      This can only be done via a Safe transaction.',
                                                                                            'params': {'handler': 'contract to handle fallbacks calls.'}},
                                                            'setup(address[],uint256,address,bytes,address,address,uint256,address)': {'details': 'Setup function sets initial storage of contract.',
                                                                                                                                       'params': {'_owners': 'List of Safe owners.',
                                                                                                                                                  '_threshold': 'Number of required confirmations for a Safe transaction.',
                                                                                                                                                  'data': 'Data payload for optional delegate call.',
                                                                                                                                                  'fallbackHandler': 'Handler for fallback calls to this contract',
                                                                                                                                                  'payment': 'Value that should be paid',
                                                                                                                                                  'paymentReceiver': 'Adddress that should receive the payment (or 0 if tx.origin)',
                                                                                                                                                  'paymentToken': 'Token that should be used for the payment (0 is ETH)',
                                                                                                                                                  'to': 'Contract address for optional delegate call.'}},
                                                            'signMessage(bytes)': {'details': 'Marks a message as signed, so that it can be used with EIP-1271',
                                                                                   'params': {'_data': 'Arbitrary length data that should be marked as signed on the behalf of address(this)'}},
                                                            'swapOwner(address,address,address)': {'details': 'Allows to swap/replace an owner from the Safe with another address.      This can only be done via a Safe transaction.',
                                                                                                   'params': {'newOwner': 'New owner address.',
                                                                                                              'oldOwner': 'Owner address to be replaced.',
                                                                                                              'prevOwner': 'Owner that pointed to the owner to be replaced in the linked list'}}},
                                                'title': 'Gnosis Safe - A multisignature wallet with support for confirmations using signed messages based on ERC191.'},
                                     'userdoc': {'methods': {'addOwnerWithThreshold(address,uint256)': {'notice': 'Adds the owner `owner` to the Safe and updates the threshold to `_threshold`.'},
                                                             'changeThreshold(uint256)': {'notice': 'Changes the threshold of the Safe to `_threshold`.'},
                                                             'disableModule(address,address)': {'notice': 'Disables the module `module` for the Safe.'},
                                                             'enableModule(address)': {'notice': 'Enables the module `module` for the Safe.'},
                                                             'isValidSignature(bytes,bytes)': {'notice': 'Implementation of ISignatureValidator (see `interfaces/ISignatureValidator.sol`)'},
                                                             'removeOwner(address,address,uint256)': {'notice': 'Removes the owner `owner` from the Safe and updates the threshold to `_threshold`.'},
                                                             'signMessage(bytes)': {'notice': 'Marks a message (`_data`) as signed.'},
                                                             'swapOwner(address,address,address)': {'notice': 'Replaces the owner `oldOwner` in the Safe with `newOwner`.'}}}},
                          'settings': {'compilationTarget': {'/gnosis-safe/contracts/GnosisSafe.sol': 'GnosisSafe'},
                                       'evmVersion': 'petersburg',
                                       'libraries': {},
                                       'optimizer': {'enabled': False, 'runs': 200},
                                       'remappings': []},
                          'sources': {'/gnosis-safe/contracts/GnosisSafe.sol': {'keccak256': '0x8c12335842166d5a6a6d320afe4ccbef706524ff38a2d0946ef92f4e33c557ae',
                                                                                'urls': ['bzz-raw://8bdb6cc4fdaf3c87426410ebd6c8a5d4042ac9a9340fcf0bca8b60a39b53f6e4',
                                                                                         'dweb:/ipfs/QmZi8d73z5Rgtwx4FJ658cTzSgfmSwYHR3ajwmzfo1HQNf']},
                                      '/gnosis-safe/contracts/base/Executor.sol': {'keccak256': '0xd2835623a200b6f14979751aff14e48362b5db0d86fff17dfb6a982790ff6c67',
                                                                                   'urls': ['bzz-raw://df85c3b4dc546ffd8790a155bf6190b55168a69f469624a9134f1e7a9e079880',
                                                                                            'dweb:/ipfs/QmXozPPHk7KAyoihdx4FEn4dEaR2x9yDJthQcZPR3Knxpv']},
                                      '/gnosis-safe/contracts/base/FallbackManager.sol': {'keccak256': '0x18baeb026940c7a06ee4aceebed0118b920468777e2f08a45d39c0983ee57523',
                                                                                          'urls': ['bzz-raw://75ec51dbc17c5e5c6701ed6809ea6c0d8bbd8dfdca944ed00d64d6f96fde98f0',
                                                                                                   'dweb:/ipfs/QmTbJz9p6oro7MCZKHBBBeoowQNYv7raQnoC5bfWxoQ4vR']},
                                      '/gnosis-safe/contracts/base/Module.sol': {'keccak256': '0x0d168bb2c28fe04185e992692705925d700ecc32692e1a1f997478c55722b9ad',
                                                                                 'urls': ['bzz-raw://72b39ab237628e99e68b89269a99efbf7f4c977ce8dcda9e947e74ffffc2bf36',
                                                                                          'dweb:/ipfs/QmekYYrv5X2wdg2QqaP96qhkxpwTT8nt47CHvuBxzHv9hp']},
                                      '/gnosis-safe/contracts/base/ModuleManager.sol': {'keccak256': '0xb37522d525b7bc868df406e3779ff764f74d74354dc8e86ad4590afb62722117',
                                                                                        'urls': ['bzz-raw://797f422109bdb6517916c41697cf834cafc14ce2bab8140b26847aa27fc95523',
                                                                                                 'dweb:/ipfs/QmNMXB1tBH9tJfmNqteUKdD8RXKXX9jNscz6Y5ijxqzGAL']},
                                      '/gnosis-safe/contracts/base/OwnerManager.sol': {'keccak256': '0x0b4e23b1ba1f82475822f9fd3c7286190219f930f8917e8c5abb7e934a2fa9ef',
                                                                                       'urls': ['bzz-raw://30adee483c783750415a0ebac930e9d97d1da49d90c52ceeb02a65263ab4d1e5',
                                                                                                'dweb:/ipfs/Qma7RcT3LfzQrdpG2uBMbpx1qQbL2TF91UfANdeGUct2AT']},
                                      '/gnosis-safe/contracts/common/Enum.sol': {'keccak256': '0x7bc6e5afb9436d9f7e376c2cdba51ca1f337e1b31c04cca5769db3a77ed40081',
                                                                                 'urls': ['bzz-raw://88b3a68baaff962b69b040af62698034bf9c99319e4a6dce71abc2c0c88fba91',
                                                                                          'dweb:/ipfs/QmTefyhXcMALQew96u7YRLQBnye9vapqkKBWxbynWpMHDM']},
                                      '/gnosis-safe/contracts/common/MasterCopy.sol': {'keccak256': '0x1577fad0dc06cb3ac2c7d66816a00d3b70c053a21ab5834ec7aceace9a7803a7',
                                                                                       'urls': ['bzz-raw://7f23c1e11ebb2fbd3b55a4074b4a9f343c0ac02b372cbbe66a90d71a88ce1885',
                                                                                                'dweb:/ipfs/QmexSrdAm4DqBjGi29yQTxSGKqJ5qC8jy1b5NJH6Zy9Cvh']},
                                      '/gnosis-safe/contracts/common/SecuredTokenTransfer.sol': {'keccak256': '0xefb71775825579db9bab375c4e620deaf266b00a3e8c49ba382551c1dc3b66e9',
                                                                                                 'urls': ['bzz-raw://4c57d5ba7c81d72c0e537e68bc957c7429110447dc307f2a4b054594d1068603',
                                                                                                          'dweb:/ipfs/QmeEYz4hKpfpHLU8D1BDutWa1ZBav2idBfhWxtXZtrb8Vp']},
                                      '/gnosis-safe/contracts/common/SelfAuthorized.sol': {'keccak256': '0x4c4f094227fc466846a97fe375c47ecdfcab050c303baeb69b5970d28db717a6',
                                                                                           'urls': ['bzz-raw://42759fe6b2433ea24fd0fbe98a144ef55e464f87861a13aa364db8a6f4a01cf1',
                                                                                                    'dweb:/ipfs/QmTWPnHdfcBbddkMJxvEvoWs3CZoKB5rtz3s8K2ii9z9CG']},
                                      '/gnosis-safe/contracts/common/SignatureDecoder.sol': {'keccak256': '0x9d6196319963155fd0a1dd45e6d4992489da251e18572c2fc62084482edb37a9',
                                                                                             'urls': ['bzz-raw://0298c7d98d2368bc99ae8d28befc8d40250fd7128f45095321d3c9e199fec74b',
                                                                                                      'dweb:/ipfs/QmPK4Q2mSnsEuv5ayyDAzURAksYXmbbALQ2Z5xUcfx1q4K']},
                                      '/gnosis-safe/contracts/external/GnosisSafeMath.sol': {'keccak256': '0xc8d2d226f9cf7d0e1bd8192e7e08c5b33c03413cf045c035b00e6665fc86d5bc',
                                                                                             'urls': ['bzz-raw://f2dc8f2f786e4e674814332f6e839d69dd282707ea0016c8349a86bbf006eb0f',
                                                                                                      'dweb:/ipfs/QmPJhejgQw2hmtCPJa5p9Dq4jbnYr3PrHx6E1T356TyYci']},
                                      '/gnosis-safe/contracts/interfaces/ISignatureValidator.sol': {'keccak256': '0xb75555e8e2bbbe38c55e164dde9761a016b0b4f1b0004b93d7ec2acd873faca4',
                                                                                                    'urls': ['bzz-raw://5985325d13e7aedb3036e9f342e740c14bf57b6202b11c2a36f95867f8c9ad5e',
                                                                                                             'dweb:/ipfs/QmTRKm25xk4jsTQHww3JtaU9fNp1BiM6SKoUNp5LrcLyo5']}},
                          'version': 1}
