# Generated by Django 4.1.3 on 2022-11-21 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_utils.fields

import gnosis.eth.django.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SafeMessage",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "message_hash",
                    gnosis.eth.django.models.Keccak256Field(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "safe",
                    gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
                ),
                ("message", models.JSONField()),
                ("proposed_by", gnosis.eth.django.models.EthereumAddressV2Field()),
                ("safe_app_id", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="SafeMessageConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "owner",
                    gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
                ),
                ("signature", gnosis.eth.django.models.HexField(max_length=5000)),
                (
                    "signature_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "CONTRACT_SIGNATURE"),
                            (1, "APPROVED_HASH"),
                            (2, "EOA"),
                            (3, "ETH_SIGN"),
                        ],
                        db_index=True,
                    ),
                ),
                (
                    "safe_message",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmations",
                        to="safe_messages.safemessage",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
                "unique_together": {("safe_message", "owner")},
            },
        ),
    ]
