# Generated by Django 4.1.3 on 2022-11-16 14:35

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("safe_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safemessageconfirmation",
            name="owner",
            field=gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
        ),
    ]
