# Generated by Django 4.2.10 on 2024-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safe_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="safemessageconfirmation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="safemessageconfirmation",
            constraint=models.UniqueConstraint(
                fields=("safe_message", "owner"),
                name="unique_safe_message_confirmation_owner",
            ),
        ),
    ]
