# Generated by Django 5.0.3 on 2024-03-20 12:54

from django.db import migrations

import safe_eth.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "safe_messages",
            "0002_alter_safemessageconfirmation_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            """
                ALTER TABLE "safe_messages_safemessageconfirmation" ALTER COLUMN "signature" TYPE bytea USING DECODE("signature", 'hex');
            """,
            reverse_sql="""
                ALTER TABLE "safe_messages_safemessageconfirmation" ALTER COLUMN "signature" TYPE text USING ENCODE("signature"::bytea, 'hex');
            """,
        ),
        migrations.AlterField(
            model_name="safemessageconfirmation",
            name="signature",
            field=safe_eth.eth.django.models.HexV2Field(max_length=5000),
        ),
    ]
