# Generated by Django 5.0.7 on 2024-07-19 12:53

from django.db import migrations

import safe_eth.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("safe_messages", "0003_alter_safemessageconfirmation_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safemessage",
            name="proposed_by",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="safemessage",
            name="safe",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(db_index=True),
        ),
        migrations.AlterField(
            model_name="safemessageconfirmation",
            name="owner",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(db_index=True),
        ),
    ]
