# Generated by Django 5.0.13 on 2025-06-20 12:09
# Contract signatures will not be valid as v1.4.1 contracts change how they are validated
# Contract signatures must be deleted from database to prevent issues

from django.db import migrations

from safe_eth.safe.safe_signature import SafeSignatureType


def delete_safe_message_contract_confirmations(apps, schema_editor):
    SafeMessageConfirmation = apps.get_model("safe_messages", "SafeMessageConfirmation")
    SafeMessageConfirmation.objects.filter(
        signature_type=SafeSignatureType.CONTRACT_SIGNATURE.value
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("safe_messages", "0005_safemessage_origin"),
    ]

    operations = [
        migrations.RunPython(
            delete_safe_message_contract_confirmations,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
