# Generated by Django 5.2.15 on 2026-07-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_messages', '0006_remove_contract_signatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safemessageconfirmation',
            name='signature_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CONTRACT_SIGNATURE'), (1, 'APPROVED_HASH'), (2, 'EOA'), (3, 'ETH_SIGN'), (4, 'SECP256R1')], db_index=True),
        ),
    ]
