# Generated by Django 5.2.17 on 2026-10-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_messages', '0007_alter_safemessageconfirmation_signature_type'),
    ]

    # `AlterField` on a ForeignKey drops and recreates the FK constraint, which validates every row
    # while locking both tables. Only the index is dropped in the database, constraints are kept.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='safemessageconfirmation',
                    name='safe_message',
                    field=models.ForeignKey(db_index=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='safe_messages.safemessage'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX "safe_messages_safemessageconfirmation_safe_message_id_1796dddc"',
                    reverse_sql='CREATE INDEX "safe_messages_safemessageconfirmation_safe_message_id_1796dddc" ON "safe_messages_safemessageconfirmation" ("safe_message_id")',
                ),
            ],
        ),
    ]
