# Generated by Django 2.0.8 on 2018-10-03 12:02

import django.db.models.deletion
import django.utils.timezone
import django_eth.models
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultisigConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('owner', django_eth.models.EthereumAddressField()),
                ('contract_transaction_hash', django_eth.models.Sha3HashField()),
                ('transaction_hash', django_eth.models.Sha3HashField()),
                ('type', models.PositiveSmallIntegerField()),
                ('block_number', models.BigIntegerField()),
                ('block_date_time', models.DateTimeField()),
                ('mined', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultisigTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('safe', django_eth.models.EthereumAddressField()),
                ('to', django_eth.models.EthereumAddressField()),
                ('value', django_eth.models.Uint256Field()),
                ('data', models.BinaryField(null=True)),
                ('operation', models.PositiveSmallIntegerField()),
                ('safe_tx_gas', django_eth.models.Uint256Field()),
                ('data_gas', django_eth.models.Uint256Field()),
                ('gas_price', django_eth.models.Uint256Field()),
                ('gas_token', django_eth.models.EthereumAddressField(null=True)),
                ('refund_receiver', django_eth.models.EthereumAddressField(null=True)),
                ('nonce', django_eth.models.Uint256Field()),
                ('mined', models.BooleanField(default=False)),
                ('execution_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='multisigtransaction',
            unique_together={('safe', 'nonce')},
        ),
        migrations.AddField(
            model_name='multisigconfirmation',
            name='multisig_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='history.MultisigTransaction'),
        ),
    ]
