# Generated by Django 3.1.4 on 2020-12-09 12:40

from django.db import migrations, models
import django.db.models.deletion
import gnosis.eth.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAbi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abi', models.JSONField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('relevance', models.SmallIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('address', gnosis.eth.django.models.EthereumAddressField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('contract_abi', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contracts.contractabi')),
            ],
        ),
    ]
