# Generated by Django 3.2.9 on 2021-12-09 16:28

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0008_ethereum_address_field_v2"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP INDEX IF EXISTS "contracts_contractabi_abi_hash_602e726b_like";
            ALTER TABLE "contracts_contractabi" ALTER COLUMN "abi_hash" TYPE bytea USING DECODE("abi_hash", 'hex');
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="contractabi",
            name="abi_hash",
            field=gnosis.eth.django.models.Keccak256Field(
                blank=True, default=None, null=True, unique=True
            ),
        ),
    ]
