# Generated by Django 3.2.12 on 2022-02-16 11:19

from django.db import migrations

import imagekit.models.fields

import safe_transaction_service.contracts.models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0009_alter_contractabi_abi_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="logo",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                default="",
                upload_to=safe_transaction_service.contracts.models.get_contract_logo_path,
            ),
        ),
    ]
