# Generated by Django 4.2 on 2023-05-03 11:04

from django.db import migrations

import imagekit.models.fields

import safe_transaction_service.contracts.models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0010_alter_contract_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="logo",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True,
                default="",
                storage=safe_transaction_service.contracts.models.get_file_storage,
                upload_to=safe_transaction_service.contracts.models.get_contract_logo_path,
            ),
        ),
    ]
