# Generated by Django 2.2.2 on 2019-07-25 08:57

from django.db import migrations, models

import gnosis.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="multisigconfirmation",
            name="signature",
            field=gnosis.eth.django.models.HexField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="multisigconfirmation",
            name="block_date_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="multisigconfirmation",
            name="block_number",
            field=gnosis.eth.django.models.Uint256Field(null=True),
        ),
        migrations.AlterField(
            model_name="multisigconfirmation",
            name="transaction_hash",
            field=gnosis.eth.django.models.Sha3HashField(null=True),
        ),
    ]
