# Generated by Django 2.2.6 on 2019-10-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20191023_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='safecontract',
            name='erc_20_block_number',
            field=models.IntegerField(default=0),
        ),
    ]
