# Generated by Django 2.2.3 on 2019-08-02 11:59

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import gnosis.eth.django.models
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190725_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumBlock',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('gas_limit', models.PositiveIntegerField()),
                ('gas_used', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('block_hash', gnosis.eth.django.models.Sha3HashField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EthereumTx',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tx_hash', gnosis.eth.django.models.Sha3HashField(primary_key=True, serialize=False, unique=True)),
                ('gas_used', gnosis.eth.django.models.Uint256Field(default=None, null=True)),
                ('_from', gnosis.eth.django.models.EthereumAddressField(db_index=True, null=True)),
                ('gas', gnosis.eth.django.models.Uint256Field()),
                ('gas_price', gnosis.eth.django.models.Uint256Field()),
                ('data', models.BinaryField(null=True)),
                ('nonce', gnosis.eth.django.models.Uint256Field()),
                ('to', gnosis.eth.django.models.EthereumAddressField(db_index=True, null=True)),
                ('value', gnosis.eth.django.models.Uint256Field()),
                ('block', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='txs', to='history.EthereumBlock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='multisigtransaction',
            name='to',
            field=gnosis.eth.django.models.EthereumAddressField(db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='MonitoredAddress',
            fields=[
                ('address', gnosis.eth.django.models.EthereumAddressField(primary_key=True, serialize=False)),
                ('initial_block_number', models.IntegerField(default=0)),
                ('tx_block_number', models.IntegerField(default=None, null=True)),
                ('events_block_number', models.IntegerField(default=None, null=True)),
                ('ethereum_tx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_addresses', to='history.EthereumTx')),
            ],
        ),
        migrations.AddField(
            model_name='multisigtransaction',
            name='ethereum_tx',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multisig_txs', to='history.EthereumTx'),
        ),
        migrations.CreateModel(
            name='InternalTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', gnosis.eth.django.models.EthereumAddressField(db_index=True, null=True)),
                ('gas', gnosis.eth.django.models.Uint256Field()),
                ('data', models.BinaryField(null=True)),
                ('to', gnosis.eth.django.models.EthereumAddressField(db_index=True, null=True)),
                ('value', gnosis.eth.django.models.Uint256Field()),
                ('gas_used', gnosis.eth.django.models.Uint256Field()),
                ('contract_address', gnosis.eth.django.models.EthereumAddressField(db_index=True, null=True)),
                ('code', models.BinaryField(null=True)),
                ('output', models.BinaryField(null=True)),
                ('refund_address', gnosis.eth.django.models.EthereumAddressField(db_index=True, null=True)),
                ('tx_type', models.PositiveSmallIntegerField(choices=[(0, 'CALL'), (1, 'CREATE'), (2, 'SELF_DESTRUCT')])),
                ('call_type', models.PositiveSmallIntegerField(choices=[(0, 'CALL'), (1, 'DELEGATE_CALL')], null=True)),
                ('trace_address', models.CharField(max_length=100)),
                ('error', models.CharField(max_length=100, null=True)),
                ('ethereum_tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_txs', to='history.EthereumTx')),
            ],
            options={
                'unique_together': {('ethereum_tx', 'trace_address')},
            },
        ),
        migrations.CreateModel(
            name='EthereumEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_index', models.PositiveIntegerField()),
                ('address', gnosis.eth.django.models.EthereumAddressField(db_index=True)),
                ('data', gnosis.eth.django.models.HexField(max_length=2048, null=True)),
                ('first_topic', gnosis.eth.django.models.Sha3HashField(db_index=True)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=gnosis.eth.django.models.Sha3HashField(), size=None)),
                ('ethereum_tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='history.EthereumTx')),
            ],
            options={
                'unique_together': {('ethereum_tx', 'log_index')},
            },
        ),
    ]
