# Generated by Django 2.2.6 on 2019-10-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_safecontract_erc_20_block_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethereumevent',
            old_name='first_topic',
            new_name='topic',
        ),
    ]
