# Generated by Django 2.2.4 on 2019-08-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_safestatus_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereumtx',
            name='status',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
