# Generated by Django 2.2.3 on 2019-08-02 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20190802_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredaddress',
            name='ethereum_tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_addresses', to='history.EthereumTx'),
        ),
        migrations.AlterField(
            model_name='multisigtransaction',
            name='ethereum_tx',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multisig_txs', to='history.EthereumTx'),
        ),
    ]
