# Generated by Django 2.2.6 on 2019-10-30 12:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20191030_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ethereumevent',
            name='data',
        ),
        migrations.AddField(
            model_name='ethereumevent',
            name='arguments',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
