# Generated by Django 2.2.3 on 2019-08-05 16:05

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20190802_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTxDecoded',
            fields=[
                ('internal_tx', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='decoded_tx', serialize=False, to='history.InternalTx')),
                ('function_name', models.CharField(max_length=256)),
                ('arguments', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='monitoredaddress',
            options={'verbose_name_plural': 'monitored_addresses'},
        ),
    ]
