# Generated by Django 2.2.8 on 2019-12-20 12:39

from django.db import migrations, models

from safe_transaction_service.history.indexers.tx_processor import (
    SafeTxProcessorProvider,
)


def set_failed_for_multisig_txs(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    safe_tx_processor = SafeTxProcessorProvider()
    MultisigTransaction = apps.get_model("history", "MultisigTransaction")
    for multisig_tx in MultisigTransaction.objects.filter(failed=None).exclude(
        ethereum_tx=None
    ):
        multisig_tx.failed = safe_tx_processor.is_failed(
            multisig_tx.ethereum_tx_id, multisig_tx.safe_tx_hash
        )
        multisig_tx.save(update_fields=["failed"])


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0004_auto_20191118_1001"),
    ]

    operations = [
        migrations.AddField(
            model_name="multisigtransaction",
            name="failed",
            field=models.NullBooleanField(default=None),
        ),
        migrations.RunPython(
            set_failed_for_multisig_txs, reverse_code=migrations.RunPython.noop
        ),
    ]
