# Generated by Django 2.2.4 on 2019-08-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_ethereumblock_parent_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multisigconfirmation',
            old_name='transaction_hash',
            new_name='multisig_transaction_hash',
        ),
        migrations.AddField(
            model_name='multisigconfirmation',
            name='ethereum_tx',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='multisig_confirmations', to='history.EthereumTx'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='multisigconfirmation',
            unique_together={('multisig_transaction_hash', 'owner')},
        ),
    ]
