# Generated by Django 2.2.3 on 2019-08-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20190805_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereumtx',
            name='transaction_index',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='internaltxdecoded',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
