# Generated by Django 2.2.4 on 2019-08-09 08:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20190807_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internaltxdecoded',
            options={'verbose_name_plural': 'internal_txs_decoded'},
        ),
        migrations.RemoveField(
            model_name='multisigtransaction',
            name='execution_date',
        ),
        migrations.RemoveField(
            model_name='multisigtransaction',
            name='mined',
        ),
        migrations.AddField(
            model_name='multisigtransaction',
            name='signatures',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='multisigconfirmation',
            name='multisig_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='history.MultisigTransaction'),
        ),
        migrations.AlterUniqueTogether(
            name='multisigconfirmation',
            unique_together={('transaction_hash', 'owner')},
        ),
        migrations.CreateModel(
            name='SafeStatus',
            fields=[
                ('internal_tx_decoded', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='safe_status', serialize=False, to='history.InternalTxDecoded')),
                ('address', gnosis.eth.django.models.EthereumAddressField()),
                ('owners', django.contrib.postgres.fields.ArrayField(base_field=gnosis.eth.django.models.EthereumAddressField(), size=None)),
                ('threshold', gnosis.eth.django.models.Uint256Field()),
            ],
            options={
                'unique_together': {('internal_tx_decoded', 'address')},
            },
        ),
        migrations.RemoveField(
            model_name='multisigconfirmation',
            name='block_date_time',
        ),
        migrations.RemoveField(
            model_name='multisigconfirmation',
            name='block_number',
        ),
        migrations.RemoveField(
            model_name='multisigconfirmation',
            name='confirmation_type',
        ),
        migrations.RemoveField(
            model_name='multisigconfirmation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='multisigconfirmation',
            name='mined',
        ),
        migrations.RemoveField(
            model_name='multisigconfirmation',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='multisigconfirmation',
            name='signature',
        ),
    ]
