# Generated by Django 2.2.4 on 2019-09-11 11:42

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_auto_20190816_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='safestatus',
            name='master_copy',
            field=gnosis.eth.django.models.EthereumAddressField(default='0x0000000000000000000000000000000000000000'),
            preserve_default=False,
        ),
    ]
