# Generated by Django 2.2.4 on 2019-08-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_auto_20190809_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaltx',
            name='call_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CALL'), (1, 'DELEGATE_CALL')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='internaltx',
            name='tx_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CALL'), (1, 'CREATE'), (2, 'SELF_DESTRUCT')], db_index=True),
        ),
    ]
