# Generated by Django 2.2.4 on 2019-08-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_auto_20190809_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internaltxdecoded',
            options={'verbose_name_plural': 'Internal Txs Decoded'},
        ),
        migrations.AlterModelOptions(
            name='monitoredaddress',
            options={'verbose_name_plural': 'Monitored Addresses'},
        ),
        migrations.AlterModelOptions(
            name='safestatus',
            options={'verbose_name_plural': 'Safe Statuses'},
        ),
    ]
