# Generated by Django 3.0.3 on 2020-02-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0008_ethereumtx_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="multisigtransaction",
            name="origin",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
