# Generated by Django 2.2.5 on 2019-09-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_safestatus_master_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereumblock',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
