# Generated by Django 3.0.3 on 2020-02-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_multisigtransaction_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='webhook',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='address',
        ),
    ]
