# Generated by Django 3.0.3 on 2020-02-26 15:08

from django.db import migrations

import safe_eth.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0009_multisigtransaction_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="address",
            field=safe_eth.eth.django.models.EthereumAddressField(
                blank=True, db_index=True
            ),
        ),
    ]
