# Generated by Django 2.2.4 on 2019-08-09 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_auto_20190809_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='safestatus',
            name='internal_tx',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='safe_status', serialize=False, to='history.InternalTx'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='safestatus',
            unique_together={('internal_tx', 'address')},
        ),
        migrations.RemoveField(
            model_name='safestatus',
            name='internal_tx_decoded',
        ),
    ]
