# Generated by Django 2.2.5 on 2019-09-19 09:28

from django.db import migrations, models
import django.db.models.deletion
import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_auto_20190917_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigconfirmation',
            name='signature',
            field=gnosis.eth.django.models.HexField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='multisigconfirmation',
            name='ethereum_tx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multisig_confirmations', to='history.EthereumTx'),
        ),
    ]
