# Generated by Django 3.0.3 on 2020-03-03 09:56

import django.contrib.postgres.fields
from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0010_auto_20200226_1508"),
    ]

    operations = [
        migrations.AddField(
            model_name="safestatus",
            name="enabled_modules",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=gnosis.eth.django.models.EthereumAddressField(),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="safestatus",
            name="fallback_handler",
            field=gnosis.eth.django.models.EthereumAddressField(
                default="0x0000000000000000000000000000000000000000"
            ),
            preserve_default=False,
        ),
    ]
