# Generated by Django 2.2.5 on 2019-09-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0011_auto_20190919_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumblock',
            name='confirmed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
