# Generated by Django 3.0.4 on 2020-04-15 10:04

import django.db.models.deletion
from django.db import migrations, models

import gnosis.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0016_multisigconfirmation_signature_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafeContractDelegate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delegate", gnosis.eth.django.models.EthereumAddressField()),
                ("delegator", gnosis.eth.django.models.EthereumAddressField()),
                ("label", models.CharField(max_length=50)),
                ("read", models.BooleanField(default=True)),
                ("write", models.BooleanField(default=True)),
                (
                    "safe_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safe_contract_delegates",
                        to="history.SafeContract",
                    ),
                ),
            ],
            options={
                "unique_together": {("safe_contract", "delegate")},
            },
        ),
    ]
