# Generated by alepc253 on 2021-12-01 13:30

from django.db import migrations, models

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0017_safecontractdelegate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaltx',
            name='error',
            field=models.CharField(max_length=255, null=True),
        )
    ]
