# Generated by Django 3.0.8 on 2020-07-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0019_transactions_data_none"),
    ]

    operations = [
        migrations.AddField(
            model_name="safemastercopy",
            name="version",
            field=models.CharField(default="unknown", max_length=20),
            preserve_default=False,
        ),
    ]
