# Generated by Django 3.1.3 on 2020-11-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0027_remove_errored_internal_txs_20201112_1547"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internaltx",
            name="call_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "CALL"),
                    (1, "DELEGATE_CALL"),
                    (2, "CALL_CODE"),
                    (3, "STATIC_CALL"),
                ],
                db_index=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="tx_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "CALL"),
                    (1, "CREATE"),
                    (2, "SELF_DESTRUCT"),
                    (3, "REWARD"),
                ],
                db_index=True,
            ),
        ),
    ]
