# Generated by Django 3.1.7 on 2021-03-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0031_webhook_new_safe"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="new_module_transaction",
            field=models.BooleanField(default=True),
        ),
    ]
