# Generated by Django 3.1.8 on 2021-04-07 11:35

from django.db import migrations


def fix_module_transactions(apps, schema_editor):
    InternalTxDecoded = apps.get_model('history', 'InternalTxDecoded')
    InternalTxDecoded.objects.filter(function_name='execTransactionFromModuleReturnData').update(processed=False)


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0035_safemastercopy_deployer'),
    ]

    operations = [
        migrations.RunPython(fix_module_transactions, reverse_code=migrations.RunPython.noop),
    ]
