# Generated by Django 3.1.8 on 2021-04-08 10:49

from django.db import migrations

from ..indexers.tx_processor import SafeTxProcessorProvider


def fix_failed_module_transactions(apps, schema_editor):
    ModuleTransaction = apps.get_model("history", "ModuleTransaction")
    safe_tx_processor = SafeTxProcessorProvider()
    for m in ModuleTransaction.objects.select_related(
        "internal_tx__ethereum_tx"
    ).iterator():
        if safe_tx_processor.is_module_failed(
            m.internal_tx.ethereum_tx, m.module, m.safe
        ):
            m.failed = True
            m.save(update_fields=["failed"])


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0036_fix_exec_from_module"),
    ]

    operations = [
        migrations.RunPython(
            fix_failed_module_transactions, reverse_code=migrations.RunPython.noop
        ),
    ]
