# Generated by Django 3.1.8 on 2021-04-29 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0038_safestatus_guard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeL2MasterCopy',
            fields=[
                ('safemastercopy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='history.safemastercopy')),
            ],
            options={
                'verbose_name_plural': 'Safe L2 master copies',
                'ordering': ['tx_block_number'],
            },
            bases=('history.safemastercopy',),
        ),
    ]
