# Generated by Django 3.2.8 on 2021-10-26 11:56

from django.db import migrations


def reprocess_module_txs(apps, schema_editor):
    ModuleTransaction = apps.get_model("history", "ModuleTransaction")
    InternalTxDecoded = apps.get_model("history", "InternalTxDecoded")
    ModuleTransaction.objects.all().delete()
    InternalTxDecoded.objects.filter(
        function_name__startswith="execTransactionFromModule"
    ).update(processed=False)


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0043_auto_20210927_1515"),
    ]

    operations = [
        migrations.RunPython(
            reprocess_module_txs, reverse_code=migrations.RunPython.noop
        ),
    ]
