# Generated by Django 3.2.8 on 2021-10-29 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0045_erc20transfer_erc721transfer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EthereumEvent",
        ),
    ]
