# Generated by Django 3.2.8 on 2021-11-26 15:57

import django.utils.timezone
from django.db import migrations, models

import gnosis.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0047_auto_20211102_1659"),
    ]

    operations = [
        migrations.AddField(
            model_name="erc20transfer",
            name="block_number",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="erc20transfer",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="erc721transfer",
            name="block_number",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="erc721transfer",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="erc20transfer",
            name="_from",
            field=gnosis.eth.django.models.EthereumAddressField(),
        ),
        migrations.AlterField(
            model_name="erc20transfer",
            name="to",
            field=gnosis.eth.django.models.EthereumAddressField(),
        ),
        migrations.AlterField(
            model_name="erc721transfer",
            name="_from",
            field=gnosis.eth.django.models.EthereumAddressField(),
        ),
        migrations.AlterField(
            model_name="erc721transfer",
            name="to",
            field=gnosis.eth.django.models.EthereumAddressField(),
        ),
        migrations.AddIndex(
            model_name="erc20transfer",
            index=models.Index(
                fields=["_from", "timestamp"], name="history_erc__from_64986c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="erc20transfer",
            index=models.Index(
                fields=["to", "timestamp"], name="history_erc_to_f32154_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="erc721transfer",
            index=models.Index(
                fields=["_from", "timestamp"], name="history_erc__from_72fb41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="erc721transfer",
            index=models.Index(
                fields=["to", "timestamp"], name="history_erc_to_02d4ab_idx"
            ),
        ),
        migrations.AlterField(
            model_name="erc20transfer",
            name="address",
            field=gnosis.eth.django.models.EthereumAddressField(),
        ),
        migrations.AlterField(
            model_name="erc721transfer",
            name="address",
            field=gnosis.eth.django.models.EthereumAddressField(),
        ),
        migrations.AddIndex(
            model_name="erc20transfer",
            index=models.Index(
                fields=["address"], name="history_erc_address_dba64d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="erc721transfer",
            index=models.Index(
                fields=["address"], name="history_erc_address_94cee3_idx"
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE "history_erc20transfer" SET (block_number, timestamp) =
            (
                SELECT "history_ethereumblock"."number", "history_ethereumblock"."timestamp"
                FROM "history_ethereumtx" INNER JOIN "history_ethereumblock" ON (
                    "history_ethereumtx"."block_id" = "history_ethereumblock"."number"
                ) WHERE "history_erc20transfer"."ethereum_tx_id" = "history_ethereumtx"."tx_hash");
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            UPDATE "history_erc721transfer" SET (block_number, timestamp) =
            (
                SELECT "history_ethereumblock"."number", "history_ethereumblock"."timestamp"
                FROM "history_ethereumtx" INNER JOIN "history_ethereumblock" ON (
                    "history_ethereumtx"."block_id" = "history_ethereumblock"."number"
                ) WHERE "history_erc721transfer"."ethereum_tx_id" = "history_ethereumtx"."tx_hash");
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
