# Generated by Django 3.2.9 on 2021-12-01 15:07

import django.contrib.postgres.fields
from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0049_block_number_internaltx_20211129_1111"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP INDEX IF EXISTS
                history_erc20transfer_ethereum_tx_id_16a6036b_like,
                history_erc721transfer_ethereum_tx_id_aa020110_like,
                history_ethereumblock_block_hash_106040a5_like,
                history_ethereumblock_parent_hash_9ffab967_like,
                history_ethereumtx__from_e36d4662_like,
                history_ethereumtx_to_9fb37c13_like,
                history_ethereumtx_tx_hash_c3adab3a_like,
                history_internaltx_contract_address_134466b3_like,
                history_internaltx_ethereum_tx_id_e6ac35ab_like,
                history_internaltx_refund_address_09530831_like,
                history_moduletransaction_module_5bf50dd1_like,
                history_moduletransaction_safe_794cf9b4_like,
                history_moduletransaction_to_041e4c7b_like,
                history_multisigconfirma_multisig_transaction_has_4c8cbf7a_like,
                history_multisigconfirma_multisig_transaction_id_43ec94d5_like,
                history_multisigconfirmation_ethereum_tx_id_71e0ab73_like,
                history_multisigtransaction_ethereum_tx_id_c8d3f1cf_like,
                history_multisigtransaction_safe_ba8bae68_like,
                history_multisigtransaction_safe_tx_hash_4d740966_like,
                history_multisigtransaction_to_e544fdbe_like,
                history_proxyfactory_address_ecff62ff_like,
                history_safecontract_address_b3109ec5_like,
                history_safecontract_ethereum_tx_id_4f63f583_like,
                history_safecontractdelegate_safe_contract_id_4389cdbf_like,
                history_safemastercopy_address_d1f56f9e_like,
                history_safestatus_address_68cd154d_like,
                history_webhook_address_94c4e540_like,
                notifications_firebasede_safecontract_id_acb5c418_like,
                notifications_firebasedeviceowner_owner_025b0ed6_like
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE "history_erc20transfer" ALTER COLUMN "_from" TYPE bytea USING DECODE(SUBSTRING("_from", 3), 'hex');
            ALTER TABLE "history_erc20transfer" ALTER COLUMN "address" TYPE bytea USING DECODE(SUBSTRING("address", 3), 'hex');
            ALTER TABLE "history_erc20transfer" ALTER COLUMN "to" TYPE bytea USING DECODE(SUBSTRING("to", 3), 'hex');
            ALTER TABLE "history_erc721transfer" ALTER COLUMN "_from" TYPE bytea USING DECODE(SUBSTRING("_from", 3), 'hex');
            ALTER TABLE "history_erc721transfer" ALTER COLUMN "address" TYPE bytea USING DECODE(SUBSTRING("address", 3), 'hex');
            ALTER TABLE "history_erc721transfer" ALTER COLUMN "to" TYPE bytea USING DECODE(SUBSTRING("to", 3), 'hex');
            ALTER TABLE "history_ethereumtx" ALTER COLUMN "_from" TYPE bytea USING DECODE(SUBSTRING("_from", 3), 'hex');
            ALTER TABLE "history_ethereumtx" ALTER COLUMN "to" TYPE bytea USING DECODE(SUBSTRING("to", 3), 'hex');
            ALTER TABLE "history_internaltx" ALTER COLUMN "_from" TYPE bytea USING DECODE(SUBSTRING("_from", 3), 'hex');
            ALTER TABLE "history_internaltx" ALTER COLUMN "contract_address" TYPE bytea USING DECODE(SUBSTRING("contract_address", 3), 'hex');
            ALTER TABLE "history_internaltx" ALTER COLUMN "refund_address" TYPE bytea USING DECODE(SUBSTRING("refund_address", 3), 'hex');
            ALTER TABLE "history_internaltx" ALTER COLUMN "to" TYPE bytea USING DECODE(SUBSTRING("to", 3), 'hex');
            ALTER TABLE "history_moduletransaction" ALTER COLUMN "module" TYPE bytea USING DECODE(SUBSTRING("module", 3), 'hex');
            ALTER TABLE "history_moduletransaction" ALTER COLUMN "safe" TYPE bytea USING DECODE(SUBSTRING("safe", 3), 'hex');
            ALTER TABLE "history_moduletransaction" ALTER COLUMN "to" TYPE bytea USING DECODE(SUBSTRING("to", 3), 'hex');
            ALTER TABLE "history_multisigconfirmation" ALTER COLUMN "owner" TYPE bytea USING DECODE(SUBSTRING("owner", 3), 'hex');
            ALTER TABLE "history_multisigtransaction" ALTER COLUMN "gas_token" TYPE bytea USING DECODE(SUBSTRING("gas_token", 3), 'hex');
            ALTER TABLE "history_multisigtransaction" ALTER COLUMN "refund_receiver" TYPE bytea USING DECODE(SUBSTRING("refund_receiver", 3), 'hex');
            ALTER TABLE "history_multisigtransaction" ALTER COLUMN "safe" TYPE bytea USING DECODE(SUBSTRING("safe", 3), 'hex');
            ALTER TABLE "history_multisigtransaction" ALTER COLUMN "to" TYPE bytea USING DECODE(SUBSTRING("to", 3), 'hex');
            ALTER TABLE "history_proxyfactory" ALTER COLUMN "address" TYPE bytea USING DECODE(SUBSTRING("address", 3), 'hex');
            SET CONSTRAINTS "history_safecontract_safe_contract_id_4389cdbf_fk_history_s" IMMEDIATE;
            ALTER TABLE "history_safecontractdelegate" DROP CONSTRAINT "history_safecontract_safe_contract_id_4389cdbf_fk_history_s";
            ALTER TABLE "history_safecontractdelegate" ADD CONSTRAINT "history_safecontractdelegate_safe_contract_id_4389cdbf_fk" FOREIGN KEY ("safe_contract_id") REFERENCES "history_safecontract" ("address") DEFERRABLE INITIALLY DEFERRED;
            -- ALTER TABLE "history_safecontract" ALTER COLUMN "address" TYPE bytea USING DECODE(SUBSTRING("address", 3), 'hex')::bytea;
            -- ALTER TABLE "history_safecontractdelegate" ALTER COLUMN "safe_contract_id" TYPE bytea USING DECODE(SUBSTRING("safe_contract_id", 3), 'hex');
            ALTER TABLE "history_safecontractdelegate" ALTER COLUMN "delegate" TYPE bytea USING DECODE(SUBSTRING("delegate", 3), 'hex');
            ALTER TABLE "history_safecontractdelegate" ALTER COLUMN "delegator" TYPE bytea USING DECODE(SUBSTRING("delegator", 3), 'hex');
            ALTER TABLE "history_safemastercopy" ALTER COLUMN "address" TYPE bytea USING DECODE(SUBSTRING("address", 3), 'hex');
            ALTER TABLE "history_safestatus" ALTER COLUMN "address" TYPE bytea USING DECODE(SUBSTRING("address", 3), 'hex');
            ALTER TABLE "history_safestatus" ALTER COLUMN "enabled_modules" TYPE bytea[] USING "enabled_modules"::bytea[];
            ALTER TABLE "history_safestatus" ALTER COLUMN "fallback_handler" TYPE bytea USING DECODE(SUBSTRING("fallback_handler", 3), 'hex');
            ALTER TABLE "history_safestatus" ALTER COLUMN "guard" TYPE bytea USING DECODE(SUBSTRING("guard", 3), 'hex');
            ALTER TABLE "history_safestatus" ALTER COLUMN "master_copy" TYPE bytea USING DECODE(SUBSTRING("master_copy", 3), 'hex');
            ALTER TABLE "history_safestatus" ALTER COLUMN "owners" TYPE bytea[] USING "owners"::bytea[];
            ALTER TABLE "history_webhook" ALTER COLUMN "address" TYPE bytea USING DECODE(SUBSTRING("address", 3), 'hex'), ALTER COLUMN "address" DROP NOT NULL;
            """
        ),
        migrations.AlterField(
            model_name="erc20transfer",
            name="_from",
            field=gnosis.eth.django.models.EthereumAddressV2Field(),
        ),
        migrations.AlterField(
            model_name="erc20transfer",
            name="address",
            field=gnosis.eth.django.models.EthereumAddressV2Field(),
        ),
        migrations.AlterField(
            model_name="erc20transfer",
            name="to",
            field=gnosis.eth.django.models.EthereumAddressV2Field(),
        ),
        migrations.AlterField(
            model_name="erc721transfer",
            name="_from",
            field=gnosis.eth.django.models.EthereumAddressV2Field(),
        ),
        migrations.AlterField(
            model_name="erc721transfer",
            name="address",
            field=gnosis.eth.django.models.EthereumAddressV2Field(),
        ),
        migrations.AlterField(
            model_name="erc721transfer",
            name="to",
            field=gnosis.eth.django.models.EthereumAddressV2Field(),
        ),
        migrations.AlterField(
            model_name="ethereumtx",
            name="_from",
            field=gnosis.eth.django.models.EthereumAddressV2Field(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ethereumtx",
            name="to",
            field=gnosis.eth.django.models.EthereumAddressV2Field(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="_from",
            field=gnosis.eth.django.models.EthereumAddressV2Field(null=True),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="contract_address",
            field=gnosis.eth.django.models.EthereumAddressV2Field(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="refund_address",
            field=gnosis.eth.django.models.EthereumAddressV2Field(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="to",
            field=gnosis.eth.django.models.EthereumAddressV2Field(null=True),
        ),
        migrations.AlterField(
            model_name="moduletransaction",
            name="module",
            field=gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
        ),
        migrations.AlterField(
            model_name="moduletransaction",
            name="safe",
            field=gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
        ),
        migrations.AlterField(
            model_name="moduletransaction",
            name="to",
            field=gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
        ),
        migrations.AlterField(
            model_name="multisigconfirmation",
            name="owner",
            field=gnosis.eth.django.models.EthereumAddressV2Field(),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="gas_token",
            field=gnosis.eth.django.models.EthereumAddressV2Field(null=True),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="refund_receiver",
            field=gnosis.eth.django.models.EthereumAddressV2Field(null=True),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="safe",
            field=gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="to",
            field=gnosis.eth.django.models.EthereumAddressV2Field(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="proxyfactory",
            name="address",
            field=gnosis.eth.django.models.EthereumAddressV2Field(
                primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="safecontract",
            name="address",
            field=gnosis.eth.django.models.EthereumAddressV2Field(
                primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="safecontractdelegate",
            name="delegate",
            field=gnosis.eth.django.models.EthereumAddressV2Field(),
        ),
        migrations.AlterField(
            model_name="safecontractdelegate",
            name="delegator",
            field=gnosis.eth.django.models.EthereumAddressV2Field(),
        ),
        migrations.AlterField(
            model_name="safemastercopy",
            name="address",
            field=gnosis.eth.django.models.EthereumAddressV2Field(
                primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="safestatus",
            name="address",
            field=gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
        ),
        migrations.AlterField(
            model_name="safestatus",
            name="enabled_modules",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=gnosis.eth.django.models.EthereumAddressV2Field(),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safestatus",
            name="fallback_handler",
            field=gnosis.eth.django.models.EthereumAddressV2Field(),
        ),
        migrations.AlterField(
            model_name="safestatus",
            name="guard",
            field=gnosis.eth.django.models.EthereumAddressV2Field(
                default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="safestatus",
            name="master_copy",
            field=gnosis.eth.django.models.EthereumAddressV2Field(),
        ),
        migrations.AlterField(
            model_name="safestatus",
            name="owners",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=gnosis.eth.django.models.EthereumAddressV2Field(), size=None
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="address",
            field=gnosis.eth.django.models.EthereumAddressV2Field(
                db_index=True, null=True
            ),
        ),
    ]
