# Generated by Django 3.2.9 on 2021-12-01 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0050_ethereum_address_field_v2_20211201_1507"),
    ]

    operations = [
        migrations.RunSQL(
            # Create function to migrate bytea[]
            """
            CREATE OR REPLACE FUNCTION array_address_parse(bytea[])
            RETURNS bytea[]
            AS
            $$
            DECLARE
               arrBytes ALIAS FOR $1;
               retVal bytea[];
            BEGIN
               IF array_upper(arrBytes, 1) is NULL THEN
                 RETURN ARRAY[]::bytea[];
               END IF;
               FOR I IN array_lower(arrBytes, 1)..array_upper(arrBytes, 1) LOOP
                 retVal[I] := decode(substring(encode(arrBytes[I], 'escape'), 3), 'hex');
               END LOOP;
            RETURN retVal;
            END;
            $$
            LANGUAGE plpgsql
               STABLE
            RETURNS NULL ON NULL INPUT;

            UPDATE "history_safestatus"
            SET
                owners = array_address_parse(owners),
                enabled_modules = array_address_parse(enabled_modules);

            UPDATE history_webhook SET address=null WHERE address='';

            DROP FUNCTION array_address_parse(bytea[]);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
            UPDATE "history_safecontract"
                SET "address" = DECODE(SUBSTRING(ENCODE("address", 'escape'), 3), 'hex');
            UPDATE "history_safecontractdelegate"
                SET "safe_contract_id" = DECODE(SUBSTRING(ENCODE("safe_contract_id", 'escape'), 3), 'hex');
            """,
            migrations.RunSQL.noop,
        ),
    ]
