# Generated by Django 3.2.12 on 2022-02-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0053_alter_webhook_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="authorization",
            field=models.CharField(
                default=None,
                help_text="Set HTTP Authorization header with the value",
                max_length=500,
                null=True,
            ),
        ),
    ]
