# Generated by Django 4.0.2 on 2022-02-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0054_webhook_authorization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multisigtransaction",
            name="origin",
            field=models.CharField(
                db_index=True, default=None, max_length=200, null=True
            ),
        ),
    ]
