# Generated by Django 3.2.12 on 2022-03-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0056_alter_multisigconfirmation_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="authorization",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Set HTTP Authorization header with the value",
                max_length=500,
                null=True,
            ),
        ),
    ]
