# Generated by Django 3.2.13 on 2022-04-27 11:11

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0060_add_eip1559_fields_20220419_0955"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafeLastStatus",
            fields=[
                (
                    "internal_tx",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="safe_last_status",
                        serialize=False,
                        to="history.internaltx",
                    ),
                ),
                (
                    "address",
                    gnosis.eth.django.models.EthereumAddressV2Field(
                        db_index=True, unique=True
                    ),
                ),
                (
                    "owners",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=gnosis.eth.django.models.EthereumAddressV2Field(),
                        size=None,
                    ),
                ),
                ("threshold", gnosis.eth.django.models.Uint256Field()),
                ("nonce", gnosis.eth.django.models.Uint256Field(default=0)),
                ("master_copy", gnosis.eth.django.models.EthereumAddressV2Field()),
                ("fallback_handler", gnosis.eth.django.models.EthereumAddressV2Field()),
                (
                    "guard",
                    gnosis.eth.django.models.EthereumAddressV2Field(
                        default=None, null=True
                    ),
                ),
                (
                    "enabled_modules",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=gnosis.eth.django.models.EthereumAddressV2Field(),
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Safe statuses",
            },
        ),
        migrations.AddIndex(
            model_name="safelaststatus",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["owners"], name="history_saf_owners_5fc97e_gin"
            ),
        ),
    ]
