# Generated by Django 3.2.13 on 2022-04-29 09:22

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models

import gnosis.eth.django.models


def init_safe_last_status(apps, schema_editor):
    SafeStatus = apps.get_model("history", "SafeStatus")
    SafeLastStatus = apps.get_model("history", "SafeLastStatus")

    # We cannot use Managers in migrations
    last_for_every_address = SafeStatus.objects.distinct("address").order_by(
        "address",
        "-nonce",
        "-internal_tx__block_number",
        "-internal_tx__ethereum_tx__transaction_index",
        "-internal_tx__trace_address",
    )

    for safe_status in last_for_every_address.iterator():
        SafeLastStatus.objects.update_or_create(
            address=safe_status.address,
            defaults={
                "internal_tx": safe_status.internal_tx,
                "owners": safe_status.owners,
                "threshold": safe_status.threshold,
                "nonce": safe_status.nonce,
                "master_copy": safe_status.master_copy,
                "fallback_handler": safe_status.fallback_handler,
                "guard": safe_status.guard,
                "enabled_modules": safe_status.enabled_modules,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0061_alter_internaltx_block_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafeLastStatus",
            fields=[
                (
                    "address",
                    gnosis.eth.django.models.EthereumAddressV2Field(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "owners",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=gnosis.eth.django.models.EthereumAddressV2Field(),
                        size=None,
                    ),
                ),
                ("threshold", gnosis.eth.django.models.Uint256Field()),
                ("nonce", gnosis.eth.django.models.Uint256Field(default=0)),
                ("master_copy", gnosis.eth.django.models.EthereumAddressV2Field()),
                ("fallback_handler", gnosis.eth.django.models.EthereumAddressV2Field()),
                (
                    "guard",
                    gnosis.eth.django.models.EthereumAddressV2Field(
                        default=None, null=True
                    ),
                ),
                (
                    "enabled_modules",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=gnosis.eth.django.models.EthereumAddressV2Field(),
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Safe last statuses",
            },
        ),
        migrations.RemoveIndex(
            model_name="safestatus",
            name="history_saf_owners_295490_gin",
        ),
        migrations.AddField(
            model_name="safelaststatus",
            name="internal_tx",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safe_last_status",
                to="history.internaltx",
            ),
        ),
        migrations.AddIndex(
            model_name="safelaststatus",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["owners"], name="history_saf_owners_5fc97e_gin"
            ),
        ),
        migrations.RunPython(
            init_safe_last_status, reverse_code=migrations.RunPython.noop
        ),
    ]
