# Generated by Django 3.2.13 on 2022-05-19 14:24

from django.db import migrations

import safe_eth.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0062_add_safe_last_status_20220429_0922"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internaltx",
            name="_from",
            field=safe_eth.eth.django.models.EthereumAddressV2Field(
                db_index=True, null=True
            ),
        ),
    ]
