# Generated by Django 3.2.13 on 2022-06-10 14:54

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0064_auto_20220523_0919"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="safelaststatus",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["enabled_modules"], name="history_saf_enabled_020fea_gin"
            ),
        ),
    ]
