# Generated by Django 3.2.13 on 2022-06-28 11:25

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0065_safelaststatus_history_saf_enabled_020fea_gin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ethereumblock",
            name="gas_limit",
            field=gnosis.eth.django.models.Uint256Field(),
        ),
        migrations.AlterField(
            model_name="ethereumblock",
            name="gas_used",
            field=gnosis.eth.django.models.Uint256Field(),
        ),
    ]
