# Generated by Django 3.2.13 on 2022-07-05 15:45

from django.db import migrations, models

import gnosis.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0066_auto_20220628_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multisigtransaction",
            name="data",
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="failed",
            field=models.BooleanField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="gas_token",
            field=gnosis.eth.django.models.EthereumAddressV2Field(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="origin",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="refund_receiver",
            field=gnosis.eth.django.models.EthereumAddressV2Field(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="signatures",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
