# Generated by Django 4.1.2 on 2022-11-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0067_auto_20220705_1545"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multisigtransaction",
            name="origin",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
