# Generated by Django 4.1.2 on 2022-11-14 18:39

import json

from django.db import migrations, models


def convert_str_to_json(apps, schema_editor):
    MultisigTransaction = apps.get_model("history", "MultisigTransaction")
    transactions = (
        MultisigTransaction.objects.exclude(origin__icontains="{")
        .filter(origin__isnull=False)
        .iterator()
    )
    for transaction in transactions:
        transaction.origin = json.dumps(transaction.origin)
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0067_auto_20220705_1545"),
    ]

    operations = [
        migrations.RunPython(
            convert_str_to_json, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="origin",
            field=models.JSONField(default=dict),
        ),
    ]
