# Generated by Django 4.1.2 on 2022-11-14 18:39

import json

from django.db import migrations, models
from django.db.models import Q


def prepare_migration_charfield_to_jsonfield(apps, schema_editor):
    MultisigTransaction = apps.get_model("history", "MultisigTransaction")
    transactions = MultisigTransaction.objects.all().iterator()
    for transaction in transactions:
        try:
            json.loads(transaction.origin)
        except Exception:
            if transaction.origin == "" or transaction.origin is None:
                transaction.origin = "{}"
            else:
                transaction.origin = json.dumps(transaction.origin)
            transaction.save()


def repair_backward_migration(apps, schema_editor):
    MultisigTransaction = apps.get_model("history", "MultisigTransaction")
    # Empty objects should be None
    MultisigTransaction.objects.filter(Q(origin="{}") | Q(origin='"{}"')).update(
        origin=None
    )
    # Remove duplicated quotes example: '"hello"'
    transactions = MultisigTransaction.objects.filter(origin__isnull=False).iterator()
    for transaction in transactions:
        value = json.loads(transaction.origin)
        if isinstance(value, str):
            transaction.origin = value
            transaction.save()


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0067_auto_20220705_1545"),
    ]

    operations = [
        migrations.RunPython(
            prepare_migration_charfield_to_jsonfield,
            reverse_code=repair_backward_migration,
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="origin",
            field=models.JSONField(default=dict),
        ),
    ]
