# Generated by Django 4.1.3 on 2023-01-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0069_indexingstatus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chain",
            fields=[
                ("chain_id", models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
