# Generated by Django 4.1.5 on 2023-02-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0070_chain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ethereumblock",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="ethereumblock",
            index=models.Index(
                condition=models.Q(("confirmed", False)),
                fields=["confirmed"],
                name="history_block_confirmed_idx",
            ),
        ),
    ]
