# Generated by Django 4.1.6 on 2023-02-15 12:49

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0071_alter_ethereumblock_confirmed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="erc20transfer",
            name="detail_hash",
            field=gnosis.eth.django.models.Keccak256Field(null=True),
        ),
        migrations.AddField(
            model_name="erc721transfer",
            name="detail_hash",
            field=gnosis.eth.django.models.Keccak256Field(null=True),
        ),
        migrations.AddField(
            model_name="internaltx",
            name="detail_hash",
            field=gnosis.eth.django.models.Keccak256Field(null=True),
        ),
    ]
