"""
Migrate Safe Apps links from apps.gnosis-safe.io -> apps-portal.safe.global

Generated by Django 4.2.1 on 2023-06-26 14:18
"""

from django.db import migrations

# No way to do this efficiently using Django's ORM, so using a raw SQL
migrate_safe_apps_links_sql = """
    UPDATE history_multisigtransaction
    SET origin = replace(origin::text, 'https://apps.gnosis-safe.io', 'https://apps-portal.safe.global')::jsonb
    WHERE origin->>'url' LIKE 'https://apps.gnosis-safe.io%'
"""

reverse_migrate_safe_apps_links_sql = """
    UPDATE history_multisigtransaction
    SET origin = replace(origin::text, 'https://apps-portal.safe.global', 'https://apps.gnosis-safe.io')::jsonb
    WHERE origin->>'url' LIKE 'https://apps-portal.safe.global%'
"""


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0072_safecontract_banned_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            migrate_safe_apps_links_sql, reverse_sql=reverse_migrate_safe_apps_links_sql
        )
    ]
