# Generated by Django 4.2.5 on 2023-10-05 09:23

from django.db import migrations

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0074_internaltx_history_internal_transfer_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="multisigtransaction",
            name="proposer",
            field=gnosis.eth.django.models.EthereumAddressV2Field(null=True),
        ),
    ]
