# Generated by Django 4.2.6 on 2023-11-06 11:27

from django.db import migrations

import safe_eth.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0076_alter_safemastercopy_deployer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safecontractdelegate",
            name="delegate",
            field=safe_eth.eth.django.models.EthereumAddressV2Field(db_index=True),
        ),
        migrations.AlterField(
            model_name="safecontractdelegate",
            name="delegator",
            field=safe_eth.eth.django.models.EthereumAddressV2Field(db_index=True),
        ),
    ]
