# Generated by Django 4.2.7 on 2024-02-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0077_alter_safecontractdelegate_delegate_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="safestatus",
            name="history_saf_address_1c362b_idx",
        ),
        migrations.AddIndex(
            model_name="multisigtransaction",
            index=models.Index(
                fields=["safe", "-nonce", "-created"],
                name="history_multisigtx_safe_sorted",
            ),
        ),
    ]
