# Generated by Django 4.2.10 on 2024-02-26 18:32

import django.db.models.deletion
from django.db import migrations, models

import gnosis.eth.django.models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0078_remove_safestatus_history_saf_address_1c362b_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_operation_hash",
                    gnosis.eth.django.models.Keccak256Field(unique=True),
                ),
                (
                    "sender",
                    gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
                ),
                ("nonce", gnosis.eth.django.models.Uint256Field()),
                ("init_code", models.BinaryField(blank=True, editable=True, null=True)),
                ("call_data", models.BinaryField(blank=True, editable=True, null=True)),
                ("call_data_gas_limit", gnosis.eth.django.models.Uint256Field()),
                ("verification_gas_limit", gnosis.eth.django.models.Uint256Field()),
                ("pre_verification_gas", gnosis.eth.django.models.Uint256Field()),
                ("max_fee_per_gas", gnosis.eth.django.models.Uint256Field()),
                ("max_priority_fee_per_gas", gnosis.eth.django.models.Uint256Field()),
                (
                    "paymaster",
                    gnosis.eth.django.models.EthereumAddressV2Field(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "paymaster_data",
                    models.BinaryField(blank=True, editable=True, null=True),
                ),
                ("signature", models.BinaryField()),
                (
                    "entry_point",
                    gnosis.eth.django.models.EthereumAddressV2Field(db_index=True),
                ),
                (
                    "ethereum_tx",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="history.ethereumtx",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sender", "-nonce"],
                        name="history_use_sender_b366ba_idx",
                    )
                ],
                "unique_together": {("sender", "nonce")},
            },
        ),
    ]
