# Generated by Django 4.2.10 on 2024-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0078_remove_safestatus_history_saf_address_1c362b_idx_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="erc20transfer",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="erc721transfer",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="internaltx",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="multisigconfirmation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="safecontractdelegate",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="safestatus",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="webhook",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="erc20transfer",
            constraint=models.UniqueConstraint(
                fields=("ethereum_tx", "log_index"), name="unique_erc20_transfer_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="erc721transfer",
            constraint=models.UniqueConstraint(
                fields=("ethereum_tx", "log_index"), name="unique_erc721_transfer_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="internaltx",
            constraint=models.UniqueConstraint(
                fields=("ethereum_tx", "trace_address"),
                name="unique_internal_tx_trace_address",
            ),
        ),
        migrations.AddConstraint(
            model_name="multisigconfirmation",
            constraint=models.UniqueConstraint(
                fields=("multisig_transaction_hash", "owner"),
                name="unique_multisig_transaction_owner_confirmation",
            ),
        ),
        migrations.AddConstraint(
            model_name="safecontractdelegate",
            constraint=models.UniqueConstraint(
                fields=("safe_contract", "delegate", "delegator"),
                name="unique_safe_contract_delegate_delegator",
            ),
        ),
        migrations.AddConstraint(
            model_name="safestatus",
            constraint=models.UniqueConstraint(
                fields=("internal_tx", "address"), name="unique_safe_tx_address_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.UniqueConstraint(
                fields=("address", "url"), name="unique_webhook_address_url"
            ),
        ),
    ]
