# Generated by Django 5.0.3 on 2024-03-20 12:54

from django.db import migrations

import safe_eth.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0079_alter_erc20transfer_unique_together_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
                ALTER TABLE "history_multisigconfirmation" ALTER COLUMN "signature" TYPE bytea USING DECODE("signature", 'hex');
            """,
            reverse_sql="""
            ALTER TABLE "history_multisigconfirmation" ALTER COLUMN "signature" TYPE text USING ENCODE("signature"::bytea, 'hex');
        """,
        ),
        migrations.AlterField(
            model_name="multisigconfirmation",
            name="signature",
            field=safe_eth.eth.django.models.HexV2Field(
                default=None, max_length=5000, null=True
            ),
        ),
    ]
