# Generated by Django 5.0.6 on 2024-06-14 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0081_internaltx_history_internal_transfer_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="safecontract",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, db_index=True
            ),
            preserve_default=False,
        ),
        migrations.RunSQL(
            """
            UPDATE "history_safecontract" SET created =
            (
                SELECT "history_ethereumblock"."timestamp"
                FROM "history_ethereumtx" INNER JOIN "history_ethereumblock" ON (
                    "history_ethereumtx"."block_id" = "history_ethereumblock"."number"
                ) WHERE "history_safecontract"."ethereum_tx_id" = "history_ethereumtx"."tx_hash");
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
