# Generated by Django 5.0.6 on 2024-07-02 11:36

from django.db import migrations, models

import safe_eth.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0082_safecontract_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduletransaction",
            name="safe",
            field=safe_eth.eth.django.models.EthereumAddressV2Field(),
        ),
        migrations.AddIndex(
            model_name="moduletransaction",
            index=models.Index(
                fields=["safe", "created"],
                include=("internal_tx_id",),
                name="history_moduletransaction_safe",
            ),
        ),
    ]
