# Generated by Django 5.0.7 on 2024-07-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0083_alter_moduletransaction_safe_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebHook",
        ),
    ]
