# Generated by Django 5.0.7 on 2024-07-19 12:53

import django.contrib.postgres.fields
from django.db import migrations

import safe_eth.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0083_alter_moduletransaction_safe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erc20transfer",
            name="_from",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="erc20transfer",
            name="address",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="erc20transfer",
            name="to",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="erc721transfer",
            name="_from",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="erc721transfer",
            name="address",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="erc721transfer",
            name="to",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="ethereumtx",
            name="_from",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ethereumtx",
            name="to",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="_from",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="contract_address",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="refund_address",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="to",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="moduletransaction",
            name="module",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(db_index=True),
        ),
        migrations.AlterField(
            model_name="moduletransaction",
            name="safe",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="moduletransaction",
            name="to",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(db_index=True),
        ),
        migrations.AlterField(
            model_name="multisigconfirmation",
            name="owner",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="gas_token",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="proposer",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="refund_receiver",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="safe",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(db_index=True),
        ),
        migrations.AlterField(
            model_name="multisigtransaction",
            name="to",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="proxyfactory",
            name="address",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="safecontract",
            name="address",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="safecontractdelegate",
            name="delegate",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(db_index=True),
        ),
        migrations.AlterField(
            model_name="safecontractdelegate",
            name="delegator",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(db_index=True),
        ),
        migrations.AlterField(
            model_name="safelaststatus",
            name="address",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                db_index=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="safelaststatus",
            name="enabled_modules",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safelaststatus",
            name="fallback_handler",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="safelaststatus",
            name="guard",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="safelaststatus",
            name="master_copy",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="safelaststatus",
            name="owners",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safemastercopy",
            name="address",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="safestatus",
            name="address",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(db_index=True),
        ),
        migrations.AlterField(
            model_name="safestatus",
            name="enabled_modules",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safestatus",
            name="fallback_handler",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="safestatus",
            name="guard",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="safestatus",
            name="master_copy",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name="safestatus",
            name="owners",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="address",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                blank=True, db_index=True, null=True
            ),
        ),
    ]
