# Generated by Django 5.0.7 on 2024-07-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0084_alter_erc20transfer__from_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebHook",
        ),
    ]
