# Generated by Django 5.0.7 on 2024-07-19 14:00

import django.db.models.deletion
from django.db import migrations, models

import gnosis.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0085_delete_webhook"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafeRelevantTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("safe", gnosis.eth.django.models.EthereumAddressBinaryField()),
                (
                    "ethereum_tx",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="history.ethereumtx",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Safe Relevant Transactions",
                "indexes": [
                    models.Index(
                        fields=["safe", "-timestamp"],
                        name="history_saf_safe_3768a5_idx",
                    )
                ],
                "unique_together": {("ethereum_tx", "safe")},
            },
        ),
    ]
