# Generated by Django 5.0.6 on 2024-08-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0086_saferelevanttransaction"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO history_saferelevanttransaction(ethereum_tx_id, timestamp, safe)
            SELECT "history_internaltx"."ethereum_tx_id" AS "ethereum_tx_id",
                "history_internaltx"."timestamp" AS "timestamp",
                "history_internaltx"."to" AS "safe"
                FROM "history_internaltx"
                JOIN "history_safecontract" ON ("to" = "history_safecontract"."address")
            WHERE "history_internaltx"."call_type" = 0
                AND "history_internaltx"."value" > 0
            ON CONFLICT DO NOTHING
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
