# Generated by Django 5.0.7 on 2024-08-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0087_fix_relevant_incoming_eth_20240801"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="erc20transfer",
            index=models.Index(
                fields=["_from", "address"], name="history_erc__from_d88198_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="erc20transfer",
            index=models.Index(
                fields=["to", "address"], name="history_erc_to_d39948_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="erc721transfer",
            index=models.Index(
                fields=["_from", "address"], name="history_erc__from_d919fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="erc721transfer",
            index=models.Index(
                fields=["to", "address"], name="history_erc_to_246e8e_idx"
            ),
        ),
    ]
