# Generated by Django 5.0.10 on 2025-03-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0090_multisigtransaction_proposed_by_delegate"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS "notifications_firebasedevice_safes" CASCADE;
            DROP TABLE IF EXISTS "notifications_firebasedevice" CASCADE;
            DROP TABLE IF EXISTS "notifications_firebasedeviceowner" CASCADE;
        """
        )
    ]
