# Generated by Django 5.0.9 on 2024-11-04 13:16

from django.db import migrations, models

import safe_eth.eth.django.models
from safe_eth.eth.constants import NULL_ADDRESS


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0090_multisigtransaction_proposed_by_delegate"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="internaltxdecoded",
            name="history_decoded_processed_idx",
        ),
        migrations.AddField(
            model_name="internaltxdecoded",
            name="safe",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                db_index=True, default=NULL_ADDRESS
            ),
            preserve_default=False,
        ),
        migrations.RunSQL(
            """
            UPDATE "history_internaltxdecoded" decoded SET safe = internal._from
            FROM "history_internaltx" internal
            WHERE internal.id = decoded.internal_tx_id
            """
        ),
        migrations.AddIndex(
            model_name="internaltxdecoded",
            index=models.Index(
                condition=models.Q(("processed", False)),
                fields=["safe"],
                name="history_decoded_processed_idx",
            ),
        ),
    ]
