# Generated by Django 5.0.13 on 2025-07-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0091_remove_notifications"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ethereumblock",
            name="history_block_confirmed_idx",
        ),
        migrations.AddIndex(
            model_name="ethereumblock",
            index=models.Index(
                condition=models.Q(("confirmed", False)),
                fields=["number"],
                name="history_block_confirmed_idx",
            ),
        ),
    ]
