# Generated by Django 5.0.13 on 2025-07-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0092_remove_ethereumblock_history_block_confirmed_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ethereumblock",
            name="timestamp",
            field=models.DateTimeField(db_index=True),
        ),
    ]
