# Generated by Django 5.0.13 on 2025-08-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0093_alter_ethereumblock_timestamp"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="internaltxdecoded",
            name="history_decoded_processed_idx",
        ),
        migrations.AddIndex(
            model_name="ethereumtx",
            index=models.Index(
                fields=["tx_hash", "transaction_index"],
                name="history_eth_tx_hash_75ca71_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="internaltx",
            index=models.Index(
                fields=["id", "block_number"], name="history_int_id_ae06e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internaltxdecoded",
            index=models.Index(
                models.Case(
                    models.When(function_name="setup", then=models.Value(0)),
                    default=models.Value(1),
                ),
                models.F("internal_tx_id"),
                condition=models.Q(("processed", False)),
                name="history_decoded_processed_idx",
            ),
        ),
    ]
