# Generated by Django 5.0.13 on 2025-08-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0093_alter_ethereumblock_timestamp"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="internaltx",
            name="history_int__from_31d634_idx",
        ),
        migrations.RemoveIndex(
            model_name="internaltxdecoded",
            name="history_decoded_processed_idx",
        ),
        migrations.AddIndex(
            model_name="internaltx",
            index=models.Index(
                fields=["_from", "timestamp", "id"], name="history_int__from_2301f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="internaltxdecoded",
            index=models.Index(
                condition=models.Q(("processed", False)),
                fields=["internal_tx_id"],
                name="history_decoded_processed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="internaltxdecoded",
            index=models.Index(
                condition=models.Q(("processed", True)),
                fields=["internal_tx_id"],
                name="history_decoded_not_proc_idx",
            ),
        ),
    ]
