# Generated by Django 5.2.5 on 2025-09-04 10:51

from django.db import migrations, models

import safe_eth.eth.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0094_remove_internaltx_history_int__from_31d634_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="internaltx",
            name="history_internaltx_value_idx",
        ),
        migrations.RemoveIndex(
            model_name="internaltx",
            name="history_int_to_e72886_idx",
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="_from",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="block_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="call_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "CALL"),
                    (1, "DELEGATE_CALL"),
                    (2, "CALL_CODE"),
                    (3, "STATIC_CALL"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="refund_address",
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="internaltx",
            name="tx_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "CALL"),
                    (1, "CREATE"),
                    (2, "SELF_DESTRUCT"),
                    (3, "REWARD"),
                ]
            ),
        ),
    ]
