# Generated by Django 5.2.8 on 2025-11-27 14:36

import safe_eth.eth.django.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0098_internaltxdecoded_setup_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='safelaststatus',
            name='module_guard',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='safestatus',
            name='module_guard',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(default=None, null=True),
        )
    ]
