# Generated by Django 5.2.9 on 2025-12-10 13:18

import safe_eth.eth.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0098_internaltxdecoded_setup_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumtx',
            name='_from',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='ethereumtx',
            name='status',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ethereumtx',
            name='to',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='internaltxdecoded',
            name='function_name',
            field=models.CharField(max_length=256),
        ),
        # Fix index naming: swap the names to match their conditions
        # history_decoded_processed_idx has processed=False (should be "not_proc")
        # history_decoded_not_proc_idx has processed=True (should be "processed")
        migrations.RenameIndex(
            model_name='internaltxdecoded',
            old_name='history_decoded_processed_idx',
            new_name='history_decoded_not_proc_idx_temp',
        ),
        migrations.RenameIndex(
            model_name='internaltxdecoded',
            old_name='history_decoded_not_proc_idx',
            new_name='history_decoded_processed_idx',
        ),
        migrations.RenameIndex(
            model_name='internaltxdecoded',
            old_name='history_decoded_not_proc_idx_temp',
            new_name='history_decoded_not_proc_idx',
        ),
    ]
