# Generated by Django 5.2.9 on 2025-12-23 11:07

import safe_eth.eth.django.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0099_alter_ethereumtx__from_alter_ethereumtx_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safelaststatus',
            name='module_guard',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='safestatus',
            name='module_guard',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(default=None, null=True),
        ),
    ]
