# Generated by Django 5.2.9 on 2026-03-31 14:17

import safe_eth.eth.django.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0100_safelaststatus_module_guard_safestatus_module_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigtransaction',
            name='payment',
            field=safe_eth.eth.django.models.Uint256Field(blank=True, default=None, null=True),
        ),
    ]
