# Generated by Django 5.2.17 on 2026-10-01 11:12

import safe_eth.eth.django.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0102_alter_multisigconfirmation_signature_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multisigconfirmation',
            name='multisig_transaction_hash',
            field=safe_eth.eth.django.models.Keccak256Field(null=True),
        ),
        migrations.AlterField(
            model_name='multisigtransaction',
            name='safe',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
        migrations.AlterField(
            model_name='safestatus',
            name='address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(),
        ),
    ]
