# Generated by Django 5.2.17 on 2026-10-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0103_alter_multisigconfirmation_multisig_transaction_hash_and_more'),
    ]

    # `AlterField` on a ForeignKey drops and recreates the FK constraint, which validates every row
    # while locking both tables. Only the index is dropped in the database, constraints are kept.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='erc20transfer',
                    name='ethereum_tx',
                    field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='history.ethereumtx'),
                ),
                migrations.AlterField(
                    model_name='erc721transfer',
                    name='ethereum_tx',
                    field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='history.ethereumtx'),
                ),
                migrations.AlterField(
                    model_name='internaltx',
                    name='ethereum_tx',
                    field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='internal_txs', to='history.ethereumtx'),
                ),
                migrations.AlterField(
                    model_name='safecontractdelegate',
                    name='safe_contract',
                    field=models.ForeignKey(db_index=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safe_contract_delegates', to='history.safecontract'),
                ),
                migrations.AlterField(
                    model_name='saferelevanttransaction',
                    name='ethereum_tx',
                    field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='history.ethereumtx'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=f'DROP INDEX "{index_name}"',
                    reverse_sql=f'CREATE INDEX "{index_name}" ON "{table}" ("{column}")',
                )
                for index_name, table, column in [
                    ("history_erc20transfer_ethereum_tx_id_16a6036b", "history_erc20transfer", "ethereum_tx_id"),
                    ("history_erc721transfer_ethereum_tx_id_aa020110", "history_erc721transfer", "ethereum_tx_id"),
                    ("history_internaltx_ethereum_tx_id_e6ac35ab", "history_internaltx", "ethereum_tx_id"),
                    ("history_safecontractdelegate_safe_contract_id_4389cdbf", "history_safecontractdelegate", "safe_contract_id"),
                    ("history_saferelevanttransaction_ethereum_tx_id_0b704cf3", "history_saferelevanttransaction", "ethereum_tx_id"),
                ]
            ],
        ),
    ]
